### ISSUE TITLE
Settings adjustment for single gene amplification

### ISSUE THREAD

**Issue by kokonech** [kharchenkolab/numbat#102]
Certain significant somatic drivers could be assoicated with amplifcation of only a single gene. Known examples are MYC/MYCN amplifications. From my analysis I could not identify such events from starndard settings in several medulloblastoma tumor samples. As noted via e-mail discussion _num_genes_ parameter could have impact here since it is n=10 by default. How to adjust this value and what about the control of false positive increase in this case? Also, are there other settings to keep in mind for this analysis?

**Comment by teng-gao** [comment]
Hi @kokonech ,

In [v1.3.0](https://github.com/kharchenkolab/numbat/releases/tag/v1.3.0) you can now force Numbat to evaluate smaller segments by providing a fixed CNV profile via [segs_consensus_fix](https://kharchenkolab.github.io/numbat/articles/numbat.html#using-existing-cnv-calls). Let me know how it goes if you end up giving it a try!
