### ISSUE TITLE
Re-define clustering or subtrees based on the computed phylogeny

### ISSUE THREAD

**Issue by kokonech** [kharchenkolab/numbat#103]
The Numbat documentation nicely describes how to adjust the parameters for initial run and also interpret the results, but are the ways to adjust the clustering without re-running full analysis? First, is it possible simply to make a different k limit in the clustering. Second, what are the ways to re-define the clustering on post processing steps? Would be great to have some documentation /examples about this.

**Comment by teng-gao** [comment]
Hi @kokonech ,

Thanks for the suggestion. Yes, that's indeed a useful feature to have. I added some experimental functionalities in the `devel` branch (https://github.com/kharchenkolab/numbat/commit/3baf8cddeaa58858a6da22fce841f041aaf83c30) for users to specify the number of cuts on the phylogeny (`n_cut`) to define clones. In general, `n` cuts will result in `n+1` clones (with the first clone always being normal diploid). You can specify `n_cut` either in the `run_numbat` workflow or via post-processing using `get_gtree` like below. Note that you need to rerun the workflow to get `nb$treeML` and `nb$P`.

```
nb = Numbat$new('~/test_numbat/results/ATC2')

for (k in 1:3) {
    
    p = plot_phylo_heatmap(
        get_gtree(nb$treeML, nb$P, n_cut = k),
        nb$joint_post,
        nb$segs_consensus
    )
    
    print(p)
}
```
![image](https://user-images.githubusercontent.com/13375875/218553823-902bb9c8-033b-4dc7-b9f9-1a55492383ff.png)
![image](https://user-images.githubusercontent.com/13375875/218553839-59bef610-87ee-449f-bca2-749e440d5bed.png)
![image](https://user-images.githubusercontent.com/13375875/218553851-da3f7f80-a69e-4b04-8d99-9acde958fb92.png)

I will incorporate this feature in the main branch and maybe add some documentation soon.
