### ISSUE TITLE
Settings for Cellsnp

### ISSUE THREAD

**Issue by Summerhythm** [kharchenkolab/numbat#105]
Hi Teng,

Thanks for developing this tool! Our group are currently run numbat on our full-length scRNA-seq data. We noticed that the setting of "--minMAF" and "--minCOUNT" are set to 0 and 2, respectively (in pileup_and_phase.R), which is smaller than settings used in cellsnp-lite tutorial (https://cellsnp-lite.readthedocs.io/en/latest/manual.html, using minMAF=0.1 & minCOUNT=20). Will this setting (0 and 2) favors the phasing step by passing more SNP to Eagle? In addition, can we try setting this to minMAF=0.1 & minCOUNT=20 if we have full-length data with a relatively high sequencing depth?

Thank you very much!

Yours,
Jack

**Comment by teng-gao** [comment]
Hi, 

> Will this setting (0 and 2) favors the phasing step by passing more SNP to Eagle?

Yes, that is the idea. For 10x the coverage is sparse and sequencing error rate is usually very low, so most variant allele seen at a known SNP position is likely real and we want to catch as many SNPs as possible for phasing to work well.

> In addition, can we try setting this to minMAF=0.1 & minCOUNT=20 if we have full-length data with a relatively high sequencing depth?

Yes, in high coverage one have to be careful about sequencing errors when genotyping, so the original settings may make more sense.

**Comment by Summerhythm** [comment]
Got it, thank you very much!
