### ISSUE TITLE
docker tags

### ISSUE THREAD

**Issue by johnyaku** [kharchenkolab/numbat#107]
Love your work, but can you guys please stop abusing the `:latest` tag for Docker images? 😃 

When I last downloaded the `latest` image it was version `v1.1.0` but I see that this has been updated two weeks ago. There was also a new release two weeks (`v1.2.2`) so I assume that `latest` now contains this version, but I'm reluctant to download 20GB just to check.

See this rant (for example) on the perils of using the `latest` tag like this: https://vsupalov.com/docker-latest-tag/

I could, of course, make my own image and tag it however I want. But it would be nicer to refer to the "official" repo

**Comment by teng-gao** [comment]
Thanks for the nudge. We'll use the package version as tags for Docker images for updates.
