### ISSUE TITLE
Run Numbat on selected chromosomes

### ISSUE THREAD

**Issue by aranham** [kharchenkolab/numbat#108]
Hi, 

I was wondering if it is possible to run Numbat on only selected chromosomes? I tried going through the documentation and issues and could not find any mention any of this. 

Thanks,
Michelle

**Comment by teng-gao** [comment]
I suppose you can subset the data (`count_mat`, `df_allele`, `lambdas_ref`) according to the chromosomes you want, although this would affect diploid estimation. It might make sense if you supply `diploid_chroms` at the same time. Anyhow, please feel free to experiment and hack this feature in if you feel that it might be useful. We'll be happy to review any PRs on this.

**Comment by aranham** [comment]
Will try by subsetting according to chromosomes and let you know. Thanks!

**Comment by teng-gao** [comment]
This is now possible with CRAN release v1.3.0. You can just supply the desired chromosomes or segments via [`segs_consensus_fix`](https://kharchenkolab.github.io/numbat/articles/numbat.html#using-existing-cnv-calls). Please note that diploid regions should also be included, however.
