### ISSUE TITLE
Where to find Eagle genetic_map_hg38_withX.txt.gz since the mirror is down?

### ISSUE THREAD

**Issue by KrGurashi** [kharchenkolab/numbat#109]
Hi all,

I would love to run numbat but I cannot download the genetic map from Eagle since the mirror is down. 

Any chance anybody could share the file somehow?

Many thanks

**Comment by teng-gao** [comment]
Hello, you can copy it from the numbat Docker. 
https://kharchenkolab.github.io/numbat/articles/numbat.html#docker

**Comment by KrGurashi** [comment]
Thanks for the prompt response! Looking forward to have a go at it

**Comment by KrGurashi** [comment]
Thanks for the prompt response! Looking forward to have a go at it
