### ISSUE TITLE
Using numbat on multiple  10x visium spatial samples

### ISSUE THREAD

**Issue by spatialbiology1** [kharchenkolab/numbat#113]
Dear Teng Gao,

Thank you for developing a great tool. I am interested in applying 10x visium on matched  primary and metastatic samples. Is there a way I can combine samples so that I can study global  and unique CNV alterations between these samples?

Thanks
Zinn

**Comment by teng-gao** [comment]
Hi @spatialbiology1 , 

Multiple Visium (for fresh tissue) samples should work similarly as scRNA-seq samples. Please checkout this related issue
https://github.com/kharchenkolab/numbat/issues/111 and the [spatial vignette](https://kharchenkolab.github.io/numbat/articles/spatial-rna.html).

Best,
Teng

**Comment by spatialbiology1** [comment]
Thank you so much. We have FFPE samples. Is there is a problem ?
Many thanks
Ashiq



Ashiq Masood, MD
Associate Professor of Medicine
Program Leader, GI Medical Oncology
Member, Center for Computational Biology and Bioinformatics,

Department of Medicine - Hematology/Oncology

Indiana University Melvin and Bren Simon Comprehensive Cancer Center

535 Barnhill Drive, Suite 473, Indianapolis, IN 46202

Phone: 317.948-7576; email: ***@***.***

Admin: Laurie Carlson

Email: ***@***.***

Lab:

Masood Lab

Health Information and Translational Sciences (HITS)

Indiana University School of Medicine

410 W 10th St, Indianapolis, IN 46202

________________________________
From: Teng Gao ***@***.***>
Sent: Tuesday, April 18, 2023 8:53 AM
To: kharchenkolab/numbat ***@***.***>
Cc: Masood, Ashiq ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [kharchenkolab/numbat] Using numbat on multiple 10x visium spatial samples (Issue #113)

This message was sent from a non-IU address. Please exercise caution when clicking links or opening attachments from external sources.


Hi @spatialbiology1<https://github.com/spatialbiology1> ,

Multiple Visium (for fresh tissue) samples should work similarly as scRNA-seq samples. Please checkout this related issue
#111<https://github.com/kharchenkolab/numbat/issues/111> and the spatial vignette<https://kharchenkolab.github.io/numbat/articles/spatial-rna.html>.

Best,
Teng

**Comment by teng-gao** [comment]
Unfortunately Visium for FFPE is probe-based and it doesn't actually sequence the transcripts (so no SNP information is captured). Expression-only methods (InferCNV/CopyKAT) would be more suitable for these samples.
