### ISSUE TITLE
Fail when running with target subset of regions

### ISSUE THREAD

**Issue by kokonech** [kharchenkolab/numbat#118]
Issue occured when providing arguments via parameter "segs_consensus_fix". Error message:

```
Running HMMs on 4 cell groups..
Error in value[[3L]](cond) : `glue` failed in `formatter_glue` on:

  'try-error' chr "Error in mutate(., seg = paste0(CHROM, generate_postfix(cumsum(boundary) +  : \n  ℹ In argument: `seg = paste0("| __truncated__ 

Raw error message:

 object 'i' not found 

Please consider using another `log_formatter` or `skip_formatter` on strings with curly braces.`glue` failed in `formatter_glue` on:

  - attr(*, "condition")=List of 6 

...

```

Without this param run on the same sample works well (even though good reference is required for correct result).

**Comment by kokonech** [comment]
The problems was lack of regions without any gains/losses in the segs_consensus_fix, including them fixed the problem.

**Comment by Gonnamu** [comment]
Hello，I meet the same problem in one sample of my data, could you tell me how to solve this error?
Thanks，
Elbert

![Image](https://github.com/user-attachments/assets/00efcd19-c24b-4a4a-af09-3f3830ae60f8)

**Comment by Gonnamu** [comment]
Hello, which outcome file can I find the information of segs_consensus_fix?
