### ISSUE TITLE
Z States output

### ISSUE THREAD

**Issue by aelhossiny** [kharchenkolab/numbat#119]
Hi, I am trying to compare events in clones from different samples to determine if I can define conserved events in certain cancer. As an oncoprint and visual inspection of the events aren't efficient approaches, I wanted to select a sample-invariant metric I can use to cluster cells/pseudobulk-clones

In the paper, Supp Fig 6, you mentioned that `"Hidden states in the Numbat joint HMM and their respective parameter configurations are marked in black solid dots. Each dashed line represents the possible expression change and allele fraction for a given genotype depending on the cell fraction and haplotype state (major or minor)." `

<img width="300" alt="image" src="https://github.com/kharchenkolab/numbat/assets/62777503/30c4cbb7-28a9-4479-a44c-e89707c49a97">

Is this emitted as one of the analysis output? and can I use it to compare/clusters cells from different samples? If not, can I use the estimated phi `phi_mle` as a measure for copy number ratio to the diploid state? 

Thanks

**Comment by teng-gao** [comment]
Hello, 

The schematic in Supp Fig 6 only applies to pseudobulk CNV calling via HMM. Both `phi_mle` and `theta_mle` are outputted in `segs_consensus`. You can check the variable descriptions for output files here:
https://kharchenkolab.github.io/numbat/articles/descriptions.html
