### ISSUE TITLE
Does Numbat filter cells out during giving posterior probabilities on single-cell level?

### ISSUE THREAD

**Issue by aelhossiny** [kharchenkolab/numbat#120]
Hi, I have noticed that some of the cells are not reported in the `joint_post` slot even though they present in the original bam file. I might have missed it somewhere in the paper or the documentation, but do you filter out cells during computing posterior probabilities on single-cell level? 

Thanks

**Comment by teng-gao** [comment]
Hi,

The only filtering for cells are here:

https://github.com/kharchenkolab/numbat/blob/a367fa55fd3ec6b516c3131b955b61e8d767a722/R/main.R#L106-L117

So, all cells in `count_mat` should be present in `joint_post` unless they have zero coverage.
