### ISSUE TITLE
Which CNV_state to use from the output?

### ISSUE THREAD

**Issue by aelhossiny** [kharchenkolab/numbat#124]
Hi,

I noticed that `joint_post` and `segs_consensus` has multiple columns for the `cnv_state`, like (`cnv_state`, `cnv_state_post`, `cnv_state_map`, `cnv_state_mle`)

Which one is used for the final CNV event call?

Thanks

**Comment by teng-gao** [comment]
Hi,

The `cnv_state` reflects state assignment from HMM Viterbi decoding, whereas `cnv_state_post` reflects posterior state assignment after optimizing the extend of allelic imbalance ($\theta$) using Forward-Backward. `cnv_state_post` is always used as the final event type assignment. `cnv_state` in `joint_post` is copied from `cnv_state_post` from `segs_consensus`. The other columns are experimental and should not be used.

Best,
Teng
