### ISSUE TITLE
analyse multiple samples from the same individual together to increase power

### ISSUE THREAD

**Issue by rosaranli** [kharchenkolab/numbat#129]
Thanks again for this wonderful tool. We had multiple samples from he same tumour and did single cell RNA sequencing. From other analysis, we knew that the samples from the same tumour share some, if not all, tumour clones. I was thinking of combining the multiple samples together to infer the CNV clones to increase power as some of the tumour samples may not have lots of cells. To do this, I combined the {sample}_allele_counts.tsv.gz from different samples and run run_numbet function but I got the error "'Inconsistent SNP genotypes; Are cells from two different individuals mixed together". I realised the error was caused that the same SNP may have different phased genotype. Just wondering since the tumour samples are from the same tumour, if they have different phased genotypes, does that mean they have different somatic mutations? If so, I would assume the cells from the same tumour sample could also have this problems as different cells may have different somatic mutations. But I never saw this happen using cells from the same tumour sample. Just wondering if you could give suggestions how to get around with this problem and analysis the cells from multiple samples together to increase the power?

**Comment by teng-gao** [comment]
Have you tried the multi-sample mode of pileup_and_phase? You can provide BAMs and other inputs in comma delimited list.
https://kharchenkolab.github.io/numbat/articles/numbat.html#preparing-data

**Comment by rosaranli** [comment]
Thank you very much for your quick reply. I thought that would generate multiple {sample}_allele_counts.tsv.gz files and cause the same problem. I will try it to see if it can solve the problem.

**Comment by rosaranli** [comment]
Problem solved by running tumour samples together and combine the df files. Thank you very much for that. Most of the samples, I seem to see more clones than expected and some of the clones look false positive to me. Is it possible to specify the number of clones detected or how to adjust the parameters if I want to reduce these false positives? Many thanks!

**Comment by teng-gao** [comment]
Hi @rosaranli ,
You can adjust the number of clones after running Numbat:
https://kharchenkolab.github.io/numbat/articles/results.html#refine-subclones-on-the-phylogeny

**Comment by rosaranli** [comment]
sorry for keep posting questions on the closed issue. I didn't express clearly. I was thinking how to change the number of clones in the bulk_clones_final.png so I could associate the clones with the allele frequency profiles.

**Comment by rosaranli** [comment]
For example, in the bulk_clones_final.png in one of my analysis, most  clones have the chr1 loss except one. But the one that show chr1 neural seems to have lower expression than  0 in terms of logFC, which indicate it may have lost chr1 or at least some of the cells in this clone. I was thinking of reducing the clone number to reevaluate the allele frequency profile.

**Comment by teng-gao** [comment]
@rosaranli Mind opening up a separate issue?
