### ISSUE TITLE
`perform_nni` uses too much memory

### ISSUE THREAD

**Issue by teng-gao** [kharchenkolab/numbat#13]
![image](https://user-images.githubusercontent.com/13375875/153247334-93c4547d-46a8-4dee-ab11-125d0e2603af.png)

**Comment by teng-gao** [comment]
Culprit:
```
> neighbours
16858 phylogenetic trees
> neighbours
4.3 Gb
```

**Comment by evanbiederstedt** [comment]
There's some issue with `phangorn` here: https://github.com/KlausVigo/phangorn/blob/master/R/treeRearrangement.R#L102-L145

Not sure precisely where the issue is; I was assuming it was a C error, but I'm not sure. Might be worth reaching out to the phangorn author Klaus Schliep
