### ISSUE TITLE
Issue about Interpretation of Results of the section Tumor phylogeny

### ISSUE THREAD

**Issue by sunshine1126** [kharchenkolab/numbat#135]
Thank you for this wonderful tool. When I read the interpretation of the results you wrote （https://kharchenkolab.github.io/numbat/articles/results.html), I don't understand this result (see the picture). 

<img width="807" alt="WechatIMG18665" src="https://github.com/kharchenkolab/numbat/assets/32659317/ffa6e7f9-10e0-41c0-9ba9-67475c9a76c0">
Grey cells are defined as normal cells, why is the number of mutations the highest? Many thanks!

**Comment by teng-gao** [comment]
Hello, the axis should be in reverse in this plot - thanks for catching this!

**Comment by sunshine1126** [comment]
> Hello, the axis should be reversed in this plot - thanks for catching this!
OK，thank you for your reply！
