### ISSUE TITLE
Why is there so much LoH in the mouse data tutorial?

### ISSUE THREAD

**Issue by thomasveith** [kharchenkolab/numbat#139]
In Numbat's walkthrough for mouse data, there is a lot of CNLoH in the results, I was wondering why is that the case? Is that to be expected for all hybrid mice, for the hybrid mouse used in the walkthrough in particular, or is there some bias in Numbat's algorithm that leads to this output with hybrid mice?
<img width="828" alt="Screenshot 2023-09-15 at 11 20 00 AM" src="https://github.com/kharchenkolab/numbat/assets/47635394/58e581ca-6c01-4bac-8e82-3a63ac84c043">

**Comment by teng-gao** [comment]
Hi,

That's a good question - I don't think this is to be expected in general or specific to hybrid mice. It's likely specific to this this tumor's biology - for example, HR-deficient tumors often have widespread LoH across the genome.

https://ascopubs.org/doi/full/10.1200/PO.16.00031
