### ISSUE TITLE
Troubleshoot Error - missing files in output directory

### ISSUE THREAD

**Issue by RaghadShu** [kharchenkolab/numbat#141]
Hello,
This is a .out file from run_numbat: 

`Loading required package: Matrix
Registered S3 methods overwritten by 'treeio':
  method              from    
  MRCA.phylo          tidytree
  MRCA.treedata       tidytree
  Nnode.treedata      tidytree
  Ntip.treedata       tidytree
  ancestor.phylo      tidytree
  ancestor.treedata   tidytree
  child.phylo         tidytree
  child.treedata      tidytree
  full_join.phylo     tidytree
  full_join.treedata  tidytree
  groupClade.phylo    tidytree
  groupClade.treedata tidytree
  groupOTU.phylo      tidytree
  groupOTU.treedata   tidytree
  is.rooted.treedata  tidytree
  nodeid.phylo        tidytree
  nodeid.treedata     tidytree
  nodelab.phylo       tidytree
  nodelab.treedata    tidytree
  offspring.phylo     tidytree
  offspring.treedata  tidytree
  parent.phylo        tidytree
  parent.treedata     tidytree
  root.treedata       tidytree
  rootnode.phylo      tidytree
  sibling.phylo       tidytree
The legacy packages maptools, rgdal, and rgeos, underpinning the sp package,
which was just loaded, will retire in October 2023.
Please refer to R-spatial evolution reports for details, especially
https://r-spatial.org/r/2023/05/15/evolution4.html.
It may be desirable to make the sf package available;
package maintainers should consider adding sf to Suggests:.
The sp package is now running under evolution status 2
     (status 2 uses the sf package in place of rgdal)
Attaching SeuratObject

Numbat version: 1.3.2.1
Scistreer version: 1.2.0
Running under parameters:
t = 1e-05
alpha = 1e-04
gamma = 20
min_cells = 50
init_k = 3
max_cost = 4642.8
n_cut = 0
max_iter = 2
max_nni = 100
min_depth = 0
use_loh = auto
segs_loh = None
call_clonal_loh = TRUE
segs_consensus_fix = None
multi_allelic = TRUE
min_LLR = 5
min_overlap = 0.45
max_entropy = 0.5
skip_nj = FALSE
diploid_chroms = None
ncores = 40
ncores_nni = 40
common_diploid = TRUE
tau = 0.3
check_convergence = FALSE
plot = TRUE
genome = hg38
Input metrics:
15476 cells
Mem used: 4.25Gb
Calling segments with clonal LOH
Approximating initial clusters using smoothed expression ..
Mem used: 4.27Gb
number of genes left: 9065
running hclust...
! # Invaild edge matrix for <phylo>. A <tbl_df> is returned.
! # Invaild edge matrix for <phylo>. A <tbl_df> is returned.
Iteration 1
Mem used: 15.9Gb
Expression noise level (MSE): high (3.2). Consider using a custom expression reference profile.
Running HMMs on 5 cell groups..
Retesting CNVs..
Retesting CNVs..
Retesting CNVs..
Retesting CNVs..
Retesting CNVs..
Running HMMs on 3 cell groups..
Testing for multi-allelic CNVs ..
0 multi-allelic CNVs found: 
Evaluating CNV per cell ..
Mem used: 6.16Gb
Excluding clonal LOH regions .. 
All cells succeeded
Expanding allelic states..
No multi-allelic CNVs, skipping ..
No multi-allelic CNVs, skipping ..
No multi-allelic CNVs, skipping ..
Building phylogeny ..
Mem used: 6.31Gb
No CNV remains after filtering by entropy in single cells. Consider increasing max_entropy.
Warning messages:
1: In asMethod(object) :
  sparse->dense coercion: allocating vector of size 1.6 GiB
2: In asMethod(object) :
  sparse->dense coercion: allocating vector of size 1.0 GiB
3: In asMethod(object) :
  sparse->dense coercion: allocating vector of size 2.3 GiB
[1] "DONE!"
`
Which seems like a successful run. However, when I try to import the out directory to R using nb = Numbat$new(out_dir = './numbat_out') I get the following error:
![Screenshot 2023-09-18 at 13 24 22](https://github.com/kharchenkolab/numbat/assets/143171933/52cc478d-38b4-403e-be50-00220f7b9e4c)

Not sure if my output directory is missing some files:
![Screenshot 2023-09-18 at 13 26 12](https://github.com/kharchenkolab/numbat/assets/143171933/9ed8d822-5dcd-474d-ba61-81c439cdbff1)

Do you have any idea what is causing this error?
Your input would be greatly appreciated,
Raghad

**Comment by teng-gao** [comment]
Hello,

As the error indicates, no CNV was detected after the filters. 


> Expression noise level (MSE): high (3.2)

This means that the reference expression profile does not match the target sample very well. You may consider using a custom reference.

> No CNV remains after filtering by entropy in single cells. Consider increasing max_entropy.

This is another recommendation that you may want to set `max_entropy` to be higher (0.5-1) to relax the filtering threshold.
