### ISSUE TITLE
High ploidy cell lines

### ISSUE THREAD

**Issue by thomasveith** [kharchenkolab/numbat#144]
In the event that we are dealing with a cell line that has very high ploidy, where almost no chromosomes are diploid, would it be advisable to flag chromosomes that are known (from Fish karyotype assays) to be triploid as the diploid arms, and then interpret the final results with that understanding? Or, how should high ploidy cell lines be dealt with in the Numbat workflow?

**Comment by teng-gao** [comment]
If almost no diploid chroms are available,  and there's likely whole genome doubling, you can supply **quadruploid** regions to `diploid_chroms`. This would probably lead to the most sensible interpretation of the CNs for other regions.

**Comment by thomasveith** [comment]
Thank you for your reply! Unfortunately, none of the regions we probed in this cell line came back as tetraploid, so we really cannot say with certainty which ones those would be (although I suspect you are correct regarding WGD and that such regions exist). Would problems arise from assigning triploid regions to `diploid_chroms`?

**Comment by teng-gao** [comment]
> Thank you for your reply! Unfortunately, none of the regions we probed in this cell line came back as tetraploid, so we really cannot say with certainty which ones those would be (although I suspect you are correct regarding WGD and that such regions exist). Would problems arise from assigning triploid regions to `diploid_chroms`?

I think triploid regions would be problematic to use as diploid reference regions because they have imbalanced haplotype ratio. If there are regions that are tetraploid (with no haplotype imbalance) Numbat should be able to find them without manually specifying `diploid_chroms`  ..

**Comment by teng-gao** [comment]
> I have a similar question/problem. After WGS, we have estimated the ploidy to be 3N, while Numbat results show most of the genome to be LOH or deleted. Would it be possible to adjust the baseline to 3 instead of 4 copies while running Numbat?
> 
> Thank you in advance!

Numbat is probably using 4N regions as baseline, which I think makes more sense than using 3N regions as baseline
