### ISSUE TITLE
Probabilities of each CNV state are missing in joint_post_2.tsv

### ISSUE THREAD

**Issue by hxj5** [kharchenkolab/numbat#146]
Hi, thanks for the great tool!

I ran Numbat (v1.2.1) on a 10x scRNA-seq dataset. The program outputs the CNV plots ("panel_2.png") without reporting any error. However, the probabilities of each CNV state (i.e., "p_amp   p_neu   p_del   p_loh   p_bamp  p_bdel") are not available in "joint_post_2.tsv".

Do you know how to get these probabilities? Thanks!

**Comment by hxj5** [comment]
The log file and the first 10 lines of "joint_post_2.tsv" are attached for your reference.

[log.txt](https://github.com/kharchenkolab/numbat/files/13222624/log.txt)
[stderr.txt](https://github.com/kharchenkolab/numbat/files/13222625/stderr.txt)
[joint_post_2.10-line.txt](https://github.com/kharchenkolab/numbat/files/13222626/joint_post_2.10-line.txt)

**Comment by teng-gao** [comment]
Hi @hxj5, they are renamed as `prior_loh`, and so on.

**Comment by hxj5** [comment]
Thanks for the quick reply. 

To clarify, we have used the same version (v1.2.1) for several 10x scRNA-seq datasets, the probabilities "p_xxx" and "prior_xxx" (e.g., `p_amp` and `prior_amp`) were always outputed together in "joint_post_2.tsv". This is the first time we found "p_xxx" are missing while "prior_xxx" are outputed. Therefore, I have three questions:

Q1. Are "p_xxx" different from "prior_xxx" (at least for v1.2.1)? Are they posterior probability for CNV states?
Q2. Can we use "prior_xxx" as final probabilities for each CNV state? if not, what CNV probabilities should we use for this dataset?
Q3. Do you have any ideas why "p_xxx" are missing only in this dataset, since we have double checked the version of Numbat is not changed?

Thank you!

**Comment by teng-gao** [comment]
Interesting, please see my revised answer above. Indeed you should use `p_xxx` for the posterior CNV probabilities in single cells not `prior_xxx`, which is the consensus CNV state prob from pseudobulk HMM calling. 

As for why it's missing, seems like it's a bug that whenever multiallelic events are called `p_xxx` are not appended to `joint_post`. I will note this to fix in the next version. For now please you can set `multiallelic = FALSE` in `run_numbat` to disable it, and the output should be normal

**Comment by hxj5** [comment]
Thanks for the answer, very helpful. The output now contains the "p_xxx" values after setting `multi_allelic = FALSE`.
