### ISSUE TITLE
 WASHU MM study Bioproject data not available

### ISSUE THREAD

**Issue by juniajvs** [kharchenkolab/numbat#149]
Dear all,

Thank you for creating such a great tool. As I was going through your Nature Biotechnology datasets, I noticed that the WASHU MM datasets is not currently available. Would you be able to send me a link that works for downloading it since the one listed in the paper doesn't work (see below)? 

https://www.ncbi.nlm.nih.gov/bioproject/?term=PRJNA694128

Thank you!

**Comment by teng-gao** [comment]
Hi @juniajvs I just checked and the SRA link in the original paper is indeed not working. Please shoot the original authors an email about this. 
Thanks, 
Teng
