### ISSUE TITLE
Compatible with mouse data?

### ISSUE THREAD

**Issue by zqzneptune** [kharchenkolab/numbat#15]
Hi, does Numbat work with mouse data? Thanks!
Johnson

**Comment by evanbiederstedt** [comment]
Hi @zqzneptune 

Yes, it is compatible with mouse data. We'll update the documentation shortly to show how to run Numbat with Mus musclus. 

We'll update you when this is done. 

Thanks, Evan

**Comment by teng-gao** [comment]
Hi Johnson, 

Thanks for your interest in Numbat! We haven't tested Numbat on mouse data so far. My impression is that most lab mice are inbred strains so they lack heterozygous SNPs (I may be wrong though). However, if your mice are hybrid crosses between two known strains (so that you have the full parental haplotypes), then in theory Numbat should work well.

Thanks,
Teng

**Comment by JBreunig** [comment]
We have published mouse tumor scRNA-seq data with numerous SNPs and CNVs if you need something to test.

**Comment by zqzneptune** [comment]
Thanks! Some guidance for accessing the data would be really appreciated.

**Comment by teng-gao** [comment]
> We have published mouse tumor scRNA-seq data with numerous SNPs and CNVs if you need something to test.

Yes, we'd be interested in testing this on our end as well.

**Comment by JBreunig** [comment]
You can download from GEO listed in here:  https://www.cell.com/cell/fulltext/S0092-8674(19)30901-8?_returnURL=https%3A%2F%2Flinkinghub.elsevier.com%2Fretrieve%2Fpii%2FS0092867419309018%3Fshowall%3Dtrue

https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE117154

Fig. S6A shows the results of inferCNV.

Or I can send looms if you prefer by Box. Please let me know how it goes!

**Comment by teng-gao** [comment]
Hi @zqzneptune and @JBreunig ,

We now have a tutorial on how to use Numbat on mouse data. Turns out that it works great for F1 hybrid mice:

https://kharchenkolab.github.io/numbat/articles/mouse.html

Best,
Teng

**Comment by zqzneptune** [comment]
Thanks for the update! We will start to test this.
