### ISSUE TITLE
Cell Ranger Count Default Intronic Counting Impact

### ISSUE THREAD

**Issue by DarioS** [kharchenkolab/numbat#155]
In Cell Ranger version 7, 10x Genomics have changed default behaviour to include intronic reads into final gene count matrix.

![image](https://github.com/kharchenkolab/numbat/assets/631218/ec141d5f-c9ff-48ae-bef9-dd262469eb3b)

For best performance, does `--include-introns false` need to be specified? Should a warning about it be in Numbat guide? From my reading of your journal article, I see that you are using Cell Ranger version 6, which doesn't count intronic reads. How important is it?

**Comment by teng-gao** [comment]
It may cause slightly more noise in the expression profiles when using default HCA reference (`ref_hca`) that comes with the package (which probably didn't include introns). Ideally, the settings should be the same in producing the custom reference profile as the target sample.
