### ISSUE TITLE
Document creation of *rda objects

### ISSUE THREAD

**Issue by evanbiederstedt** [kharchenkolab/numbat#16]
For reproducibility, users should know how all *rda objects were created. 

I'm immediately skeptical when I see these files without some code + comments which explains how these objects were created. 

Users should be able to create each *rda object following code which is in this file: https://github.com/kharchenkolab/numbat/tree/main/raw-data

Here's an example from conos: https://github.com/kharchenkolab/conos/blob/main/data-raw/create_rdata_file.R

**Files for documentation:**
- [x] count_mat_ATC2.rda	
- [x] gtf_hg19.rda		
- [x] ref_hca_counts.rda
- [x] df_allele_ATC2.rda	
- [x] gtf_hg38.rda		
- [x] vcf_meta.rda
- [x] genetic_map_hg19.rda	
- [x] genetic_map_hg38.rda	
- [x] ref_hca.rda

**Comment by teng-gao** [comment]
Done.
