### ISSUE TITLE
Error in find_common_diploid(bulks, gamma = gamma, alpha = alpha, ncores = ncores) :    Error in smooth_segs(., min_genes = min_genes) :

### ISSUE THREAD

**Issue by whitneyt1** [kharchenkolab/numbat#163]
`> #Run Numbat
> out=run_numbat(count_mat = mat_clean,
+                lambdas_ref = numbat_ref_N2535,
+                df_allele = df_allele,
+                genome = 'hg38',
+                t=1e-5,
+                max_entropy = 0.8,
+                ncores=4,
+                plot = TRUE,
+                out_dir = './Numbat_Outs/outs/'
+               
+   
+ )

Numbat version: 1.3.2.1
Scistreer version: 1.2.0
Running under parameters:
t = 1e-05
alpha = 1e-04
gamma = 20
min_cells = 50
init_k = 3
max_cost = 1246.2
n_cut = 0
max_iter = 2
max_nni = 100
min_depth = 0
use_loh = auto
segs_loh = None
call_clonal_loh = FALSE
segs_consensus_fix = None
multi_allelic = TRUE
min_LLR = 5
min_overlap = 0.45
max_entropy = 0.8
skip_nj = FALSE
diploid_chroms = None
ncores = 4
ncores_nni = 4
common_diploid = TRUE
tau = 0.3
check_convergence = FALSE
plot = TRUE
genome = hg38
Input metrics:
4154 cells
Mem used: 2.16Gb
Approximating initial clusters using smoothed expression ..
Mem used: 2.16Gb
number of genes left: 12099
running hclust...
! # Invaild edge matrix for <phylo>. A <tbl_df> is returned.                                                                         
! # Invaild edge matrix for <phylo>. A <tbl_df> is returned.
Iteration 1
Mem used: 7.2Gb
High SNP contamination detected (72.9%). Please make sure that cells from only one individual are included in genotyping step.
Expression noise level (MSE): medium (1.4). 
Running HMMs on 5 cell groups..
Error in find_common_diploid(bulks, gamma = gamma, alpha = alpha, ncores = ncores) : 
  Error in smooth_segs(., min_genes = min_genes) : 
  No segments containing more than 10 genes for CHROM 13,21.
In addition: Warning message:
In mclapply(bulks %>% split(.$sample), mc.cores = ncores, function(bulk) { :
  scheduled cores 2, 1 encountered errors in user code, all values of the jobs will be affected`

Hello, I am getting this error once run_numbat begins trying to run HMMs. 

 I am using numbat on a series of 10X Visium lung cancer tissues. my normal reference is a normal lung tissues 10X visium reaction. I have ensured the gene names are in the same format between the reference and test. 

This is the script i used to loop through reactions to perform the pileup step.
<img width="1212" alt="Screen Shot 2024-02-09 at 7 57 00 PM" src="https://github.com/kharchenkolab/numbat/assets/46573884/5e6c1ca7-2380-4eab-9f41-18ad4e005520">
 Thank you!

**Comment by whitneyt1** [comment]
Hello, I have been unable to address this issue still. Is there any additional information I can provide?

**Comment by teng-gao** [comment]
Hello, if your Visium data is probed based chemistry Numbat doesn’t support this

**Comment by whitneyt1** [comment]
hi @teng-gao  it is not probe based, it is 3' sequencing on frozen sections. Thanks!

**Comment by teng-gao** [comment]
Seems that the SNP profile looks aberrant:
```
High SNP contamination detected (72.9%). Please make sure that cells from only one individual are included in genotyping step.
```
It's hard to tell what the issue is however only based on this message ..

**Comment by whitneyt1** [comment]
Thank you, @teng-gao 
these visium reactions are individual patient tumors. Is there any additional information I can provide that would be helpful to deduce the issue? thanks!

**Comment by whitneyt1** [comment]
I identified that I was following the mouse tutorial for human spatial data and did not phase my human data appropriately as per the "Getting Started" vignette. After running pileup_and_phase.R correctly, it resolved this issue.
