### ISSUE TITLE
compute time for pileup_and_phase.R script

### ISSUE THREAD

**Issue by cathalgking** [kharchenkolab/numbat#167]
When running the pre-processing script (pileup_and_phase.R) it is taking quite a long time to compute. After 24 hours the output SLURM log file: 
```[I::csp_fetch_core][Thread-1] 26.00% SNPs processed.```
Its 10x single-cell data and the BAM file for that sample is ~4G in size and that sample has 1,665 cells. Its running on our HPC with 64G of memory being used. Is this normal? Are there any ways to speed up processing time?

**Comment by cathalgking** [comment]
After ~24 hours of running on the same sample, the script appeared to complete (```All Done!```) but then is followed by an Error ```Error in `mutate()`:
ℹ In argument: `snp_index = 1:n()`.
Caused by error:
! `snp_index` must be size 0 or 1, not 2.```
The full output is shown below:
```{bash}
[I::csp_fetch_core][Thread-3] 98.00% SNPs processed.
[I::csp_fetch_core][Thread-5] 98.00% SNPs processed.
[I::main] All Done!
[I::main] Version: 1.2.3 (htslib 1.19)
[I::main] CMD: cellsnp-lite -s /homes/cathal.king/Myeloma/Laura/fastqs/patient_1/CR_P1_CD38/outs/possorted_genome_bam.bam -b /homes/cathal.king/yard/apps/cellranger-7.1.0/lib/python/cellranger/barcodes/737K-august-2016.txt -O /homes/cathal.king/Myeloma/numbat/test2/pileup/CR_P1_CD38 -R /homes/cathal.king/Myeloma/numbat/genome1K.phase3.SNP_AF5e2.chr1toX.hg38.vcf -p 32 --minMAF 0 --minCOUNT 2 --UMItag Auto --cellTAG CB
[I::main] end time: 2024-02-28 14:51:35
[I::main] time spent: 94829 seconds.
character(0)
Creating VCFs
Error in `mutate()`:
ℹ In argument: `snp_index = 1:n()`.
Caused by error:
! `snp_index` must be size 0 or 1, not 2.
Backtrace:
     ▆
  1. ├─numbat:::genotype(...)
  2. │ ├─... %>% arrange(CHROM, POS)
  3. │ └─base::lapply(...)
  4. │   └─numbat (local) FUN(X[[i]], ...)
  5. │     └─numbat:::get_snps(vcf)
  6. │       └─... %>% filter(!is.na(AR))
  7. ├─dplyr::arrange(., CHROM, POS)
  8. ├─dplyr::mutate(., AR = AD/DP)
  9. ├─dplyr::summarise(...)
 10. ├─dplyr::group_by(., CHROM, POS, REF, ALT, snp_id)
 11. ├─dplyr::bind_rows(.)
 12. │ └─rlang::list2(...)
 13. ├─dplyr::filter(., !is.na(AR))
 14. ├─dplyr::mutate(., AR = AD/DP)
 15. ├─dplyr::mutate(., snp_index = 1:n())
 16. ├─dplyr:::mutate.data.frame(., snp_index = 1:n())
 17. │ └─dplyr:::mutate_cols(.data, dplyr_quosures(...), by)
 18. │   ├─base::withCallingHandlers(...)
 19. │   └─dplyr:::mutate_col(dots[[i]], data, mask, new_columns)
 20. │     └─mask$eval_all_mutate(quo)
 21. │       └─dplyr (local) eval()
 22. ├─dplyr:::dplyr_internal_error(...)
 23. │ └─rlang::abort(class = c(class, "dplyr:::internal_error"), dplyr_error_data = data)
 24. │   └─rlang:::signal_abort(cnd, .file)
 25. │     └─base::signalCondition(cnd)
 26. └─dplyr (local) `<fn>`(`<dpl:::__>`)
 27.   └─rlang::abort(message, class = error_class, parent = parent, call = error_call)
Execution halted
```
Can you advice what went wrong here?
@teng-gao

**Comment by cathalgking** [comment]
I have tried this again on two more samples and still get the same error as shown above. However, there does seem to be some output from this step in the 'pileup' folder as shown here:
```cellSNP.base.vcf  cellSNP.samples.tsv  cellSNP.tag.AD.mtx  cellSNP.tag.DP.mtx  cellSNP.tag.OTH.mtx```
However, there does not seem to be much in those files and the vcf file only has the header line. 
The script seems to be processing through the data (log shows x% SNPs processed ...).
Have you any suggestions of what I can do here? @teng-gao

**Comment by teng-gao** [comment]
Hi it’s possible that the chr prefix of BAMs doesn’t match that of the SNP file
Or if the 10x library is probe based chemistry for FFPE this would also happen

**Comment by cathalgking** [comment]
Thanks for your reply @teng-gao 
The Chemistry for this data is ```"Single Cell 3’ v3"```.
The first record of the BAM file is shown here:
<img width="1488" alt="Screenshot 2024-04-05 at 12 58 42 PM" src="https://github.com/kharchenkolab/numbat/assets/32261323/d95b2488-7a25-4740-9b84-af7a06085414">
The snp vcf file that I am using is ```genome1K.phase3.SNP_AF5e2.chr1toX.hg38.``` and some of it is shown below here:

<img width="904" alt="Screenshot 2024-04-05 at 12 58 23 PM" src="https://github.com/kharchenkolab/numbat/assets/32261323/38f739f5-6796-4be4-81b3-299de05050b1">

Do you think anything looks odd with this data?

**Comment by teng-gao** [comment]
Looks ok.. It’s also possible that the list of cell barcodes do not match those in the BAM or not in the right format (each barcode on its own line)

**Comment by cathalgking** [comment]
The list of cell barcodes where? In my BAM they are shown next to the CB flag. How can I check this? @teng-gao

**Comment by teng-gao** [comment]
I think you gave the wrong file to —barcodes argument to pileup and phase. It should be list of cell barcodes in the 10x CellRanger count output folder not the whitelist

**Comment by cathalgking** [comment]
Ok, just get them from the ```/outs/filtered_feature_bc_matrix/barcodes.tsv.gz``` file?
@teng-gao

**Comment by cathalgking** [comment]
Thanks @teng-gao That was the issue.
