### ISSUE TITLE
Excluding segs_loh causes multiple CNV states for the same segment

### ISSUE THREAD

**Issue by teng-gao** [kharchenkolab/numbat#183]
Hello! 

I am receiving this same error:
<img width="351" alt="image" src="https://github.com/kharchenkolab/numbat/assets/46573884/6daea3a3-06a6-4e44-94cd-c6e67ee406c7">

Should each seg be completely unique instead of having 1718 counts per segment?
<img width="1476" alt="image" src="https://github.com/kharchenkolab/numbat/assets/46573884/68606829-879c-47de-b862-ef4fc38f5e9f">

but it seems like my columns of P are unique? 
<img width="556" alt="image" src="https://github.com/kharchenkolab/numbat/assets/46573884/8b285d1a-5b3a-4a07-a021-c075b50c4f34">

Thank you @teng-gao

_Originally posted by @whitneyt1 in https://github.com/kharchenkolab/numbat/issues/68#issuecomment-2048531228_

**Comment by teng-gao** [comment]
@whitneyt1 This was indeed a bug where the logic for excluding `segs_loh` in `get_exp_post` causes duplicate segments in `exp_post` .. for now you can turn off `call_clonal_loh` and the run should finish. Will try to come up with a complete fix soon

**Comment by whitneyt1** [comment]
hi @teng-gao 
numbat v 1.4.1 has fixed this issue! thank you very much for your quick response and fix! It is much appreciated
