### ISSUE TITLE
Input only the gene expression matrix

### ISSUE THREAD

**Issue by Moey-git** [kharchenkolab/numbat#187]
Hi, TengGao@teng-gao,
I am very interested in your research, but I have encountered some problems. I wonder if it is possible to run numbat with just the gene expression matrix and no allele file？I would like to know how numbat-exp in Figure 2d in your article is made.

![image](https://github.com/kharchenkolab/numbat/assets/118874224/66dcef00-0657-4d05-8f05-c874229a4c55)

 I am looking forward to hearing from you and I would appreciate it very much. Best regards！

**Comment by teng-gao** [comment]
Hi, for Fig 2d we only benchmarked CNV detection from pseudobulk using the haplotype-aware Hidden Markov model. I have a parameter in the internal function [here](https://github.com/kharchenkolab/hahmmr/blob/02103dd622e0ea4bf3d17982ec5fdf6ddb2a6004/R/hahmmr.R#L543) that allows expression-only analysis. The overall Numbat workflow does not support expression-only mode.

**Comment by Moey-git** [comment]
Thank you for your prompt reply！

**Comment by ypershad** [comment]
Hi Teng,

Related to this issue - we have sequenced some samples with 10x Flex, the probe-based scRNAseq platform. Therefore, we only have an expression matrix and do not know alleles.

Is there a way we can try to infer single-cell losses and gains without pseudobulking?

We do have the somatic copy-number variant chromosome and cell fraction in the samples from running a bulk somatic CNV caller on WGS data.

Thanks in advance for any insights!
Yash
