### ISSUE TITLE
error with genotype function

### ISSUE THREAD

**Issue by amr15** [kharchenkolab/numbat#19]
Hi, 
Do you have any suggestions on the following error popping up after running the genotype function in the pileup_and_phase.R script?

Error in as.list.default(X) : 
  no method for coercing this S4 class to a vector

VCF files from cellsnplite seem to be fine.
Thanks!

**Comment by teng-gao** [comment]
Thanks for reporting this. My best guess is that there was an issue with the `bind_rows` here:
https://github.com/kharchenkolab/numbat/blob/main/R/genotyping.R#L9-L12
Maybe the objects were not in the right class. To debug, I would manually read in the vcf and check if `get_snps(vcf)` gives the desired result (a data.frame with SNP information). 
Any additional information would be helpful.
