### ISSUE TITLE
run_numbat() with multiple samples

### ISSUE THREAD

**Issue by kobolock** [kharchenkolab/numbat#196]
Hello,

I would like to obtain the numbat results for a patient composed of 2 samples (diagnosis/relapse).
According to your recommandations in your tutorial : 

```
  --label LABEL        Individual label. One per run.
  --samples SAMPLES    Sample name(s); comma delimited if multiple. 
                       All samples must belong to the same individual.
  --bams BAMS          BAM file(s); one per sample, comma delimited if multiple.
  --barcodes BARCODES  Cell barcode file(s); one per sample, 
                       comma delimited if multiple.
```

I executed the command below for **patient1** with the 2 samples **diagnosis** and **relapse** 

```
Rscript /numbat/inst/bin/pileup_and_phase.R \
    --label patient1 \
    --samples patient1_diagnosis,patient1_relapse \
    --bams /mnt/mydata/patient1_diagnosis.bam,/mnt/mydata/patient1_relapse.bam \
    --barcodes /mnt/mydata/patient1_diagnosis_barcodes.tsv,/mnt/mydata/patient1_relapse_barcodes.tsv \
    --outdir /mnt/mydata/patient1 \
    --gmap /Eagle_v2.4.1/tables/genetic_map_hg38_withX.txt.gz \
    --snpvcf /data/genome1K.phase3.SNP_AF5e2.chr1toX.hg38.vcf \
    --paneldir /data/1000G_hg38 \
    --ncores ncores
```
I obtained 2 differents files (patient1_diagnosis_allele_counts.tsv.gz AND patient1_relapse_allele_counts.tsv.gz) as advertised : "_If multiple samples from the same individual were provided, there will be one allele count file for each sample_"

Now, I need your help for the next :)

How execute the numbat_run() with these 2 files (allele_counts.tsv.gz) ?
(For the _count matrix_, it was not a problem to process the samples together)

```
# run
out = run_numbat(
    count_mat, 
    ref_hca,
    df_allele, 
    genome = "hg38",
    t = 1e-5,
    ncores = 4,
    plot = TRUE,
    out_dir = './test'
)
```

Is it possible to do this type of analysis (@teng-gao) ?
 
Thank you in advance for your help :)

Sam

**Comment by teng-gao** [comment]
you just `bind_rows` them together
