### ISSUE TITLE
other parameters to adjust when [1] "No CNV remains after filtering by LLR in pseudobulks. Consider reducing min_LLR."? 

### ISSUE THREAD

**Issue by whitneyt1** [kharchenkolab/numbat#199]
Hello! 

I am running numbat on 36 lung tumor cryo visium reactions. My normal reference is a at tumor-adjacent "normal" visium reaction that has been confirmed to be tumor-free by a pathologist. My samples that I am inputting into numbat have been annotated by a pathologist and confirmed to have tumor present. Two of the samples receive the error/warning [1] "No CNV remains after filtering by LLR in pseudobulks. Consider reducing min_LLR." I have tried adjusting the min_LLR value, but even at 0.5, i am unable to successfully run these tissues through numbat. Do you have any advice on other parameters to adjust? Thank you! 

`numbat version: 1.4.1
scistreer version: 1.2.0
hahmmr version: 1.0.0
Running under parameters:
t = 1e-05
alpha = 1e-04
gamma = 20
min_cells = 50
init_k = 3
max_cost = 807.8
n_cut = 0
max_iter = 2
max_nni = 100
min_depth = 0
use_loh = auto
segs_loh = None
call_clonal_loh = TRUE
segs_consensus_fix = None
multi_allelic = TRUE
min_LLR = 0.5
min_overlap = 0.45
max_entropy = 0.8
skip_nj = FALSE
diploid_chroms = None
ncores = 20
ncores_nni = 20
common_diploid = FALSE
tau = 0.2
check_convergence = FALSE
plot = TRUE
genome = hg38
Input metrics:
4039 cells
Mem used: 1.5Gb
Calling segments with clonal LOH
No segments with clonal LOH detected
Approximating initial clusters using smoothed expression ..
Mem used: 1.5Gb
number of genes left: 12443
running hclust...
Iteration 1                                                                                                                          
Mem used: 6.32Gb
Expression noise level (MSE): low (0.21). 
Running HMMs on 5 cell groups..
No CNV remains after filtering by LLR in pseudobulks. Consider reducing min_LLR.
[1] "No CNV remains after filtering by LLR in pseudobulks. Consider reducing min_LLR."`

**Comment by whitneyt1** [comment]
![image](https://github.com/user-attachments/assets/94461290-e477-4a96-8cb7-f0a7de778b84)
Here is what my bulk_subtrees_1.png looks like

**Comment by nsariipek** [comment]
Hey, did you ever figure this out?

**Comment by teng-gao** [comment]
Hi, if you see this message and the pseudobulk profiles look clean it just means no CNVs are detected
