### ISSUE TITLE
Normalizing count matrices

### ISSUE THREAD

**Issue by aelhossiny** [kharchenkolab/numbat#205]
Do I need to normalize any count matrix fed into the algorithm? or provide the raw counts? Also, can I use more than one sample in the reference count matrix that is fed to aggregate_counts() function?

follow up: I see that in aggregate_counts() you just sum gene counts for a given type and normalize by the colSums, since I have multiple samples in the reference, do you think it's better to provide normalized count matrix to the function?

Thanks

**Comment by teng-gao** [comment]
> Do I need to normalize any count matrix fed into the algorithm? or provide the raw counts?

no need to normalize, raw counts are expected

>Also, can I use more than one sample in the reference count matrix that is fed to aggregate_counts() function?

Yes, if you want to differentiate cells of the same cell type between samples, you can just annotate them differently in the `annot` argument you provide. for example, T cells from two different samples can be annotated (`group` column) as T_sample1, T_sample2

**Comment by aelhossiny** [comment]
But it's not advised to label all T-cells from different samples similarly as "T_cells"? correct?

**Comment by teng-gao** [comment]
Either way is ok. By differentiating T cells from different samples you can potentially smooth out batch-specific expression differences. However if you have too few T cells from each sample it's better to combine them by labeling them all as just T cells. No normalization is required in either case

**Comment by aelhossiny** [comment]
Great! Thanks
