### ISSUE TITLE
matched samples analysis

### ISSUE THREAD

**Issue by nandobonf** [kharchenkolab/numbat#206]
Dear authors, 
thanks for this very useful tool.
I am running the analysis of matched samples and successfully phased and pileup'd with the multiple sample mode.
Now, I read from #196  that the two "allele_counts.tsv.gz" can be just bound together (bind_rows).
What instead for the two _count matrix_ files? Is it ok to do the same (bind_cols) ? Or do they require some kind of normalization?
Thanks in advance for the reply.

**Comment by teng-gao** [comment]
No need to normalize. You can just column-bind raw count matrices of the samples you want to analyze
