### ISSUE TITLE
Run_numbat unable to successfully get through more than one iteration (no clone_post_x.tsv file generated) 

### ISSUE THREAD

**Issue by amr15** [kharchenkolab/numbat#24]
Hi , 
I'm getting this error when running "run_numbat"  
`Error in dcast.data.table(., cell + clone_opt + GT_opt + p_opt ~ clone,  :
Can not cast an empty data.table`

and I think that I'm failing  with the "cell_to_clone" function since I don't see a  clone_post_x.tsv file in my output directory.  I tried changing the max_iter to one when running this function, but that did not help.  

Do you have any suggestions?
Thanks!
Anu

**Comment by teng-gao** [comment]
Hi Anu, 

Could you show us your log.txt? And have you tried the devel version yet?

Thanks,
Teng

**Comment by amr15** [comment]
I haven't tried the devel version yet! I'll try that.  

Here's my log: 
t = 0.001
alpha = 1e-04
gamma = 20
min_cells = 10
init_k = 3
sample_size = 1e+05
max_cost = 707.7
max_iter = 1
min_depth = 0
use_loh = auto
multi_allelic = TRUE
min_LLR = 50
max_entropy = 0.6
skip_nj = TRUE
exclude_normal = FALSE
diploid_chroms = 
ncores = 10
common_diploid = TRUE
Input metrics:
2359 cells
INFO [2022-03-18 12:14:26] Approximating initial clusters using smoothed expression ..
INFO [2022-03-18 13:01:29] running hclust...
INFO [2022-03-18 13:01:34] Iteration 1
INFO [2022-03-18 15:16:51] Running HMMs on 5 cell groups..
INFO [2022-03-18 15:16:53] diploid regions: 1a,2a,3a,11a,16a
INFO [2022-03-18 16:55:09] Running HMMs on 3 cell groups..
INFO [2022-03-18 16:55:11] diploid regions: 2a
INFO [2022-03-18 16:55:14] less than 5% of genome is in neutral region - including LOH in baseline
INFO [2022-03-18 16:55:18] Testing for multi-allelic CNVs ..
INFO [2022-03-18 16:55:18] 0 multi-allelic CNVs found: 
INFO [2022-03-18 16:55:18] Making plots..
INFO [2022-03-18 16:55:31] Evaluating CNV per cell ..
INFO [2022-03-18 16:59:54] All cells succeeded
INFO [2022-03-18 16:59:57] Expanding allelic states..
INFO [2022-03-18 16:59:57] No multi-allelic CNVs, skipping ..
INFO [2022-03-18 16:59:57] No multi-allelic CNVs, skipping ..
INFO [2022-03-18 16:59:57] No multi-allelic CNVs, skipping ..
INFO [2022-03-18 16:59:58] Building phylogeny ..
INFO [2022-03-18 16:59:58] Using 2 CNVs to construct phylogeny
INFO [2022-03-18 16:59:58] Only computing UPGMA..
INFO [2022-03-18 16:59:58] Using UPGMA tree as seed..
INFO [2022-03-18 17:00:05] Iter 2 -623.1858175024 6.7

**Comment by teng-gao** [comment]
Seems like this is an edge case that's not properly handled in the `main` branch - I remember fixing something related in `devel`. Let me know if you run into the same error using the `devel` branch.

**Comment by teng-gao** [comment]
Hi @amr15 following up to see if this was fixed?

**Comment by amr15** [comment]
Hi, 
I'm still having this issue. Additionally, none of the output files have been created for iteration '2' .  Are there any other parameters you think could be changed that might help with the original error? 
Thanks!
Anu

**Comment by teng-gao** [comment]
Hi Anu,

This seems like a bug - is there a way you can share your output folder (e.g. via dropbox)? My email is `tgaoteng@gmail.com`.

Thanks,
Teng
