### ISSUE TITLE
Error while using custom reference expression

### ISSUE THREAD

**Issue by aranham** [kharchenkolab/numbat#29]
I have an error when I run numbat with a custom reference expression rather than the one that comes with the package. Could you provide some guidance?
I am attaching the log file. The following was the error message:
...
number of genes left: 10296
number of genes left: 10324
Running HMMs on 5 cell groups..
Error in `mutate()`:
! Problem while computing `seg_index = 1:n()`.
✖ `seg_index` must be size 0 or 1, not 2.
Backtrace:
     ▆
  1. ├─numbat::run_numbat(...)
  2. │ └─bulk_subtrees %>% ...
  3. ├─numbat::run_group_hmms(...)
  4. │ └─numbat::find_common_diploid(...)
  5. │   └─bulks %>% annot_consensus(segs_consensus)
  6. ├─numbat::annot_consensus(., segs_consensus)
  7. │ └─... %>% select(-any_of(c("sample")))
  8. ├─dplyr::select(., -any_of(c("sample")))
  9. ├─dplyr::distinct(., snp_id, .keep_all = TRUE)
 10. ├─dplyr::left_join(...)
 11. ├─dplyr:::left_join.data.frame(...)
 12. │ └─dplyr::auto_copy(x, y, copy = copy)
 13. │   ├─dplyr::same_src(x, y)
 14. │   └─dplyr:::same_src.data.frame(x, y)
 15. │     └─base::is.data.frame(y)
 16. ├─segs_consensus %>% mutate(seg_index = 1:n())
 17. ├─dplyr::mutate(., seg_index = 1:n())
 18. ├─dplyr:::mutate.data.frame(., seg_index = 1:n())
 19. │ └─dplyr:::mutate_cols(.data, dplyr_quosures(...), caller_env = caller_env())                                                                 
 20. │   ├─base::withCallingHandlers(...)
 21. │   └─mask$eval_all_mutate(quo)
 22. ├─dplyr:::dplyr_internal_error(...)
 23. │ └─rlang::abort(class = c(class, "dplyr:::internal_error"), dplyr_error_data = data)
 24. │   └─rlang:::signal_abort(cnd, .file)
 25. │     └─base::signalCondition(cnd)
 26. └─dplyr `<fn>`(`<dpl:::__>`)
 27.   └─rlang::abort(...)
Execution halted

[log.txt](https://github.com/kharchenkolab/numbat/files/8427516/log.txt)

**Comment by teng-gao** [comment]
Could you share the custom reference expression with me as an `.rds`?

Thanks,
Teng

**Comment by aranham** [comment]
Shared on dropbox. 

Thanks

**Comment by teng-gao** [comment]
Resolved offline - please use `aggregate_counts` function within the Numbat package to create custom reference expression profiles instead of Seurat.  The reference profiles should be library-size normalized expression rates (gene counts divided by total depth).
