### ISSUE TITLE
Problem while computing `cnv_state_post = ...[]

### ISSUE THREAD

**Issue by MigleMi** [kharchenkolab/numbat#31]
Thank you for this package! However I got an error while running it and not sure where the problem was. Since I do not know which cels are cancer cells, I used copykat results as reference groups and at first it seem to work but after a certain step got this:
...
number of genes left: 11018
Fitted reference proportions:
aneuploid:1,diploid:7.6e-05,not_assigned:7.6e-05
number of genes left: 10736
Finishing..
Finishing..
Finishing..
Finishing..
Finishing..
Finishing..
Finishing..
Finishing..
Error in mutate(., cnv_state_post = c("loh", "amp", "del", "bamp", "bdel")[which.max(c(p_loh,  :
  Problem while computing `cnv_state_post = ...[]`.
✖ `cnv_state_post` must be size 1, not 0.
ℹ Did you mean: `cnv_state_post = list(...[])` ?
ℹ The error occurred in row 41.
 
`Backtrace:
     ▆
  1. ├─numbat::run_numbat(...)
  2. │ └─numbat::retest_bulks(...)
  3. │   └─bulks %>% run_group_hmms(run_hmm = F) %>% ...
  4. ├─dplyr::mutate(., LLR = ifelse(is.na(LLR), 0, LLR))
  5. ├─numbat::run_group_hmms(., run_hmm = F)
  6. │ └─... %>% ungroup()
  7. ├─dplyr::ungroup(.)
  8. ├─dplyr::mutate(., seg_start_index = min(snp_index), seg_end_index = max(snp_index))
  9. ├─dplyr::group_by(., seg, sample)
 10. └─dplyr::bind_rows(.)
 11.   ├─tibble::as_tibble(dots)
 12.   └─tibble:::as_tibble.list(dots)
 13.     └─tibble:::lst_to_tibble(x, .rows, .name_repair, col_lengths(x))
 14.       └─tibble:::recycle_columns(x, .rows, lengths)
 15.         └─rlang::cnd_signal(...)
`
Thank you!

**Comment by teng-gao** [comment]
Hi @MigleMi,

Thanks for reporting this. Could you attach your full `log.txt`? Additionally, did you include the normal cells as input to `run_numbat` (they shouldn't be included if they are used as reference)?

Thanks,
Teng

**Comment by MigleMi** [comment]
Dear Teng, 

Thanks for quick response. No I haven't filtered those cells from the count_matrix. I guess then there should not be  aggregated counts for aneuploid cells in a reference data as well. Also, what if I don't have a good reference in my data (epithelial cells in this case) but a very few cells that are immune cells? Is it better to find a similar reference, or immune cells will do fine? Thank you again for a cool tool and all the help!
[log.txt](https://github.com/kharchenkolab/numbat/files/8612774/log.txt)

**Comment by teng-gao** [comment]
Yes, please filter out reference cells from the `count_matrix` and `df_allele`. For external reference, you could use `ref_hca` which ships with the package, which contains epithelial cells and immune cells from the Lung Human Cell Atlas. Generally, variation between cell types is greater than the same cell type between experiments, so you should do fine with an external reference with matched cell type if you don't have good internal references.
