### ISSUE TITLE
CNVs are not detected

### ISSUE THREAD

**Issue by ccruizm** [kharchenkolab/numbat#44]
Good day,

I have tried your tool and for many samples works like a charm. However, in some cases are not able to detect CNVs that are present (seen in WES and also other iCNV tools (e.g., copyKAT)). One example, the image below shows the iCNV determined by copyKAT but numbat could not identify them (attached log file).

Is there a way that by changing some parameters, those CNVs can be detected by numbat? What are other reasons why numbat can not detect them?

Thanks in advance!

![Sample_1](https://user-images.githubusercontent.com/37718031/193851075-9ebde5f4-c958-4619-9fb5-5c2da050eb09.jpeg)
[log.txt](https://github.com/kharchenkolab/numbat/files/9708007/log.txt)

**Comment by ccruizm** [comment]
Thanks @teng-gao, for the detailed answer! Below the bulk_subtrees_1.png

![bulk_subtrees_1](https://user-images.githubusercontent.com/37718031/193865294-de85882e-4cc7-443f-b64a-8d6d3693d27d.png)

I will give a try to the several recommendations/options you have given! 

It is a wonderful tool, and I am really happy with the performance! And kudos for the publication!

**Comment by teng-gao** [comment]
Thanks @ccruizm! Based on the pseudobulk profiles, the allelic frequency is quite balanced on all chromosomes so I suspect there aren't actually CNVs there (does WES show allelic imbalance?). The only other possibility is that all CNVs are balanced gains and losses, which is extremely rare.

**Comment by ccruizm** [comment]
I am waiting for the WES report. In the meantime, I checked the exp_roll_clust.png, which looks pretty similar to the one from copyKAT. 
![exp_roll_clust](https://user-images.githubusercontent.com/37718031/194268454-7525b783-e539-46f5-bf11-a8648b958320.png)
I increased the k_init (10) and now it detected some iCNV but actually they seems to be inverted of what the expression heatmaps show.
![panel_1](https://user-images.githubusercontent.com/37718031/194346997-639937e3-3164-41a1-a0d9-889635659c81.png)
What do you think might be the reason of this incongruency? Thanks again for your help!
