### ISSUE TITLE
Generate single-cell likelihoods for a pre-specified CNV

### ISSUE THREAD

**Issue by tobyaicher** [kharchenkolab/numbat#45]
Hi,

Is there a way to input a specific chosen CNV (for instance deletion or amplification of a chromosome of interest) and direct Numbat to generate single-cell likelihoods for this CNV? My understanding is that Numbat only generates single-cell likelihoods for the CNVs that are detected and pass filtering. But I would be interested in looking at single-cell likelihoods for CNVs that don't make it past these two steps (as these two steps rely on pseudobulk profiles, and I am interested in very rare subclonal events that may be present in only 1 or 2 cells in the data). 

Thank you!

**Comment by teng-gao** [comment]
Hi @tobyaicher,

Thanks for the issue. In general, it would be desirable to have a mode where users can supply a segment file containing CNVs of interest (e.g. CNV calls from DNA analysis). The main loop would just skip the HMM step. I marked this as a feature to add.

For rare and non-clonal CNVs, the expression signal probably carries most of the information. You probably just need this function here:
https://github.com/kharchenkolab/numbat/blob/main/R/main.R#L352-L359

**Comment by teng-gao** [comment]
This is now possible with CRAN release v1.3.0. You can just supply the desired chromosomes or segments via [segs_consensus_fix](https://kharchenkolab.github.io/numbat/articles/numbat.html#using-existing-cnv-calls). Please note that diploid regions should also be included, however.
