### ISSUE TITLE
Compatibility with Probe based chemistry 

### ISSUE THREAD

**Issue by afvallejo** [kharchenkolab/numbat#48]
@teng-gao Thank you for this wonderful tool.  I'm curious if this tool is compatible with the new FRP from 10X, which is a probe-based chemistry.Do you have any knowledge or opinions on this?

**Comment by teng-gao** [comment]
Hi @afvallejo, 

Thanks for the question. To my understanding of their [documentation](https://support.10xgenomics.com/single-cell-gene-expression/software/pipelines/latest/what-is-frp), the new 10x fixed RNA protocol only sequences the synthetic probes targeting each gene transcript but not the transcript cDNA themselves. So this means that we won’t get any SNP information from the individual, and allele-specific analysis is not possible.

Hope that 10x can come up with a sequence-based protocol soon ..

Best,
Teng
