### ISSUE TITLE
Error during 2. Iteration [multiplexing]

### ISSUE THREAD

**Issue by Thapeachydude** [kharchenkolab/numbat#49]
Hello, 

I'm running into an error during the second iteration. Curiously, the error doesn't occur for other samples in the dataset and also not for this one when `segs_loh = NULL`. So, it appears to be an issue for this combination of sample, reference and segs_loh. 

```
Iteration 2
Mem used: 10.3Gb
Running HMMs on 5 cell groups..
Running HMMs on 4 cell groups..                                                                                                      
less than 5% of genome is in neutral region - including LOH in baseline
Testing for multi-allelic CNVs ..
0 multi-allelic CNVs found: 
Evaluating CNV per cell ..
Mem used: 10.5Gb
Excluding clonal LOH regions .. 
All cells succeeded
Expanding allelic states..
No multi-allelic CNVs, skipping ..
No multi-allelic CNVs, skipping ..
No multi-allelic CNVs, skipping ..
Building phylogeny ..
Mem used: 10.6Gb
Using 6 CNVs to construct phylogeny
Using UPGMA tree as seed..
Mem used: 10.6Gb
Iter 2 -1496.78014009687 0.16s
Iter 3 -1496.78014009687 0.11s
Found 1 normal cells..
Error:
! Tibble columns must have compatible sizes.
• Size 46923: Column `2`.
• Size 94963: Column `3`.
ℹ Only values of size one are recycled.
Run `rlang::last_error()` to see where the error occurred.
There were 16 warnings (use warnings() to see them)

```

The `subtrees_2.rds` and `clones_2.rds` files can be found in the output directory, but not `bulk_clones_final.tsv.gz`. Therefore, I assume the error occurs somewhere in between. 

I'm running numbat using a custom reference (normalized expression values) from a public dataset. 

```
ref_internal <- aggregate_counts(refCountMat, refAnnoTab)

bulk <- get_bulk(count_mat = patMat,
                   lambdas_ref = ref_internal,
                   df_allele = alleleCounts, gtf = gtf_hg38 
  )

segs_loh <- bulk %>% detect_clonal_loh(t = 1e-4)


run_numbat(
      count_mat = patMat,
      lambdas_ref = ref_internal, 
      df_allele = alleleCounts,
      segs_loh = segs_loh,
      genome = "hg38", gamma = 20, min_cells = 50, multi_allelic = TRUE,
      t = 1e-5, max_iter = 2, max_nni = 100, min_LLR = 5,
      max_entropy = 0.5, tau = 0.3,
      ncores = 10, 
      plot = TRUE
    )
```
Any help would be appreciated. : )

**Comment by teng-gao** [comment]
Hi @Thapeachydude,

This is probably because running HMM on a pseudobulk consisting only 1 cell triggers an error. Please feel free to send me a reproducible example and I'll try to fix.

Best,
Teng

**Comment by Thapeachydude** [comment]
Hi @teng-gao 

thanks for the quick reply! Yes, the panel_2.png is plotted. 

The normalized count matrix and the reference pseudo-bulk can be found [here](https://polybox.ethz.ch/index.php/s/ukefxYFCySBAybs).

On another note: 
For some of the individuals multiple samples were distributed across different 10x lanes. For them, I ran the allele-counting as specified, providing all the bam files and single cell barcodes. I got a different `allele_count.tsv.gz` for each 10x "lane". Running numbat for all of them at the same time unfortunately causes an error: 

```
ERROR [2022-11-01 11:58:30] Inconsistent SNP genotypes; Are cells from two different individuals mixed together?

 Error in log_err("Inconsistent SNP genotypes; Are cells from two different individuals mixed together?") : 
  Inconsistent SNP genotypes; Are cells from two different individuals mixed together?
```
 
 Would you have a suggestion for how to deal with multiple samples for an individual? Do I have to call CNVs for them individually? (that would make comparison between samples a bit challenging, right?). 

Many thanks!

**Comment by teng-gao** [comment]
Thanks, I will take a look. It seems that only the last step (plotting subclone-level HMM profiles) is affected and all the other outputs should still be fine.

**Comment by teng-gao** [comment]
Hi @Thapeachydude,

I took a look at your bulk HMM profile aggregating all cells, and it seems that the allele dataframe is contaminated by many homozygous SNPs. This usually happens when multiple individual's SNPs are mixed together in `pileup_and_phase` step. How did you produce the allele count dataframe and are you sure that only cells from one individual is included?

![image](https://user-images.githubusercontent.com/13375875/200385423-f7563a0f-ab37-4bd5-9773-103881c4ae11.png)

Thanks,
Teng

**Comment by Thapeachydude** [comment]
Hi @teng-gao, 

we have a multiplexed 10x lane (8-10 individuals). For each individual I provided the bam file and barcodes for that 10x lane and then filtered the resulting allele counts for the cells of that individual. 

I guess this is where the SNP mixes come from. The issue, I tried to re-run the allele counting, with the bam for the lane (so all individuals), but only the barcodes for the individual I'm doing the allele counting on, but this results in an error. 

```
I::main] CMD: cellsnp-lite -s /main/cellranger_output/UQPQIX/outs/per_sample_outs/UQPQIX/count/sample_alignments.bam -b /main/numbat/barcodes_single/D0_P0683_UQPQIX_barcodes-single.txt -O /main/numbat/allele_counts/D0_P0683/pileup/UQPQIX -R /data/genome1K.phase3.SNP_AF5e2.chr1toX.hg38.vcf -p 10 --minMAF 0 --minCOUNT 2 --UMItag Auto --cellTAG CB
[I::main] end time: 2022-11-11 02:25:54
[I::main] time spent: 6363 seconds.
Error in `mutate()`:
! Problem while computing `snp_index = 1:n()`.
✖ `snp_index` must be size 0 or 1, not 2.
Backtrace:
     ▆
  1. ├─numbat:::genotype(label, samples, vcfs, glue("{outdir}/phasing"))
  2. │ ├─... %>% arrange(CHROM, POS)
  3. │ └─base::lapply(...)
  4. │   └─numbat (local) FUN(X[[i]], ...)
  5. │     └─numbat:::get_snps(vcf)
  6. │       └─... %>% filter(!is.na(AR))
  7. ├─dplyr::arrange(., CHROM, POS)
  8. ├─dplyr::mutate(., AR = AD/DP)
  9. ├─dplyr::summarise(...)
 10. ├─dplyr::group_by(., CHROM, POS, REF, ALT, snp_id)
 11. ├─dplyr::bind_rows(.)
 12. │ └─rlang::list2(...)
 13. ├─dplyr::filter(., !is.na(AR))
 14. ├─dplyr::mutate(., AR = AD/DP)
 15. ├─dplyr::mutate(., snp_index = 1:n())
 16. ├─dplyr:::mutate.data.frame(., snp_index = 1:n())
 17. │ └─dplyr:::mutate_cols(.data, dplyr_quosures(...), caller_env = caller_env())
 18. │   ├─base::withCallingHandlers(...)
 19. │   └─mask$eval_all_mutate(quo)
 20. ├─dplyr:::dplyr_internal_error(...)
 21. │ └─rlang::abort(class = c(class, "dplyr:::internal_error"), dplyr_error_data = data)
 22. │   └─rlang:::signal_abort(cnd, .file)
 23. │     └─base::signalCondition(cnd)
 24. └─dplyr (local) `<fn>`(`<dpl:::__>`)
 25.   └─rlang::abort(...)
Execution halted
```

Based on another issue posted, I assume this is because the barcodes in the .txt and .bam files are no longer identical then. 
Would this mean I have to subset the .bam files as well? and if so, do you know of a tool on how to do that?

Best and many thanks

**Comment by teng-gao** [comment]
Hi @Thapeachydude,

Yes, that explains it. Providing only the barcode for each individual while using the same bam should be fine.

**Comment by Thapeachydude** [comment]
Hi @teng-gao, 

re-ran things per individual with only the barcodes for that specific individual and it worked. Output looks a lot better (was wondering about the high rate of CNLoh). Thanks for taking a look!

Only a minor question remains: I spotted some calls of "bamp", what exactly would that mean? bi-allelic amplicifaction?

**Comment by teng-gao** [comment]
Yes, BAMP is balanced gains of both homologous chromosomes such as 2:2 (tetraploid) and 3:3, and so on.

**Comment by Thapeachydude** [comment]
Cool, again many thanks!
