### ISSUE TITLE
Generate count_mat with Bulk RNA-seq data

### ISSUE THREAD

**Issue by ChengHsiangLu** [kharchenkolab/numbat#53]
Hello,

I'm a beginner in bioinformatics and I have an issue with creating a workable count_mat with my bulk RNA-seq data.

First, I used your ready-to-run Docker container. then, I ran
```
Rscript /numbat/inst/bin/pileup_and_phase.R \
    --label CPM00000383-BM-R_20210510 \
    --samples CPM00000383-BM-R_20210510 \
    --bams /mnt/mydata/CPM00000383-BM-R_20210510.bam \
    --outdir /mnt/mydata/CPM00000383-BM-R_20210510 \
    --gmap /Eagle_v2.4.1/tables/genetic_map_hg38_withX.txt.gz \
    --snpvcf /data/genome1K.phase3.SNP_AF5e2.chr1toX.hg38.vcf \
    --paneldir /data/1000G_hg38 \
    --ncores 10 \
    --bulk
```

it generated CPM00000383-BM-R_20210510_allele_counts.tsv.gz within my outdir.

After that, I tried to go on with my next steps which are get_bulk and run_numbat on my Rstudio local machine. However, these steps both require count_mat. you mention that count_mat is a gene x cell raw count matrix. I was wondering if is there any suggested way to generate count_mat with my bulk RNA-seq data. Thank you.

Best,
Sam

**Comment by teng-gao** [comment]
Hi Sam,

For the bulk RNA-seq, you only need to provide a 1-column count matrix (rows are genes), with sample name as the column name. For generating transcript/gene counts, you can look into `featureCounts` and other tutorials.

Best,
Teng

**Comment by ChengHsiangLu** [comment]
Hi Teng,

I've created my 1-column count matrix with ```featureCounts```. However, after creating my count_mat and df_allele, it still shows an error when I try run_numbat. 

The code I use is as follows:
```
library(numbat)
library(Matrix)
library(dplyr)

## count_mat by featureCounts
CPM00000383_count_mat <- as.matrix((read.table("/Users/samuellu/Desktop/Labs/CHLA_Lab/Numbat/CPM00000383-BM-R_20210510/count_mat.csv", sep = ",")))
colnames(CPM00000383_count_mat) <- c('CPM00000383-BM-R_20210510')
CPM00000383_count_mat_dgC <- as(CPM00000383_count_mat, "dgCMatrix") 

## df_allele
CPM00000383_df_allele <- as.data.frame(read.table("/Users/samuellu/Desktop/Labs/CHLA_Lab/Numbat/CPM00000383-BM-R_20210510/CPM00000383-BM-R_20210510_allele_counts.tsv", sep = "\t", header = T))


bulk <- get_bulk(
  count_mat = CPM00000383_count_mat_dgC,
  lambdas_ref = ref_hca,
  df_allele = CPM00000383_df_allele,
  gtf = gtf_hg38)

segs_loh <- bulk %>% detect_clonal_loh(t = 1e-4)


out <- run_numbat(
  CPM00000383_count_mat_dgC, 
  ref_hca, 
  CPM00000383_df_allele, 
  ncores = 4,
  plot = TRUE,
  out_dir = './test/CPM00000383',
  segs_loh = segs_loh
)
```

This is the error message I got after run_numbat.
```
Running under parameters:
t = 1e-05
alpha = 1e-04
gamma = 20
min_cells = 50
init_k = 3
max_cost = 0.3
max_iter = 2
max_nni = 100
min_depth = 0
use_loh = auto
multi_allelic = TRUE
min_LLR = 5
min_overlap = 0.45
max_entropy = 0.5
skip_nj = FALSE
diploid_chroms = 
ncores = 4
ncores_nni = 4
common_diploid = TRUE
tau = 0.3
check_convergence = FALSE
plot = TRUE
genome = hg38
Input metrics:
1 cells
Mem used: 0.414Gb
Approximating initial clusters using smoothed expression ..
Mem used: 0.414Gb
number of genes left: 9313
Error in (function (cond)  : 
  error in evaluating the argument 'x' in selecting a method for function 't': subscript out of bounds
```

Can you share with me where is the problem that causes this error?

Thanks,
Sam

**Comment by teng-gao** [comment]
Hi Sam, 

You do not need to run the `run_numbat` workflow in bulk RNA-seq analysis, as it is meant for decomposing clones in scRNA-seq. You only need to run `analyze_bulk` after you make the bulk profile using `get_bulk` (as you did before for `detect_clonal_loh`).

**Comment by ChengHsiangLu** [comment]
Thank you so much!

**Comment by ChengHsiangLu** [comment]
Hi Teng,

I have problems applying numbat:::get_segs_consensus() into my script.

Thank you for your earlier suggestions. I followed your suggestions for generating gene counts using featureCounts with one bulk RNA-seq data and went through get_bulk(), analyze_bulk(), and plot_bulks(). This is my script:

```
library(numbat)
library(Matrix)
library(dplyr)
library(data.table)
library(ggplot2)
library(glue)
library(ggtree)
library(stringr)
library(tidygraph)
library(patchwork)

setwd("/Users/samuellu/Desktop/Labs/CHLA_Lab/Numbat/CPM00000383-BM-R_20210510/")

## count_mat
CPM00000383_count_mat <- as.matrix((read.table("/Users/samuellu/Desktop/Labs/CHLA_Lab/Numbat/CPM00000383-BM-R_20210510/count_mat.csv", sep = ",")))
colnames(CPM00000383_count_mat) <- c('CPM00000383-BM-R_20210510')
CPM00000383_count_mat_dgC <- as(CPM00000383_count_mat, "dgCMatrix")  # compressed sparse column CSC

## df_allele
CPM00000383_df_allele = fread("./CPM00000383-BM-R_20210510_allele_counts.tsv")

## get_bulk
CPM00000383_bulk <- get_bulk(
  count_mat = CPM00000383_count_mat_dgC,
  lambdas_ref = ref_hca,
  df_allele = CPM00000383_df_allele,
  gtf = gtf_hg38)

## analyze_bulk
CPM00000383_bulk_analyzed <- analyze_bulk(CPM00000383_bulk, t = 1e-5)

plot_bulks(CPM00000383_bulk_analyzed)
```

And this is my plot here:

![320029752_1169426373961661_7441585407310876550_n](https://user-images.githubusercontent.com/89505688/207969243-ffe3e3bc-8ae1-42f8-ba2a-ad1ed8455a52.png)

Then, I would like to use numbat:::get_segs_consensus() in my script as the description in this link:

https://rdrr.io/github/kharchenkolab/Numbat/man/get_segs_consensus.html

but, I got this error that I could not solve for days. Is there anything wrong with my CPM00000383_bulk? Do you have any suggestions on this problem? and what I should try next?

```
numbat:::get_segs_consensus(CPM00000383_bulk, min_LLR = 5, min_overlap = 0.45, retest = TRUE)
Error in `group_by()`:
! Must group by variables found in `.data`.
✖ Column `seg` is not found.
```
Thank you,

Sam
