### ISSUE TITLE
"No CNV remains after filtering" using default settings on 10x lymphoma data

### ISSUE THREAD

**Issue by juliashay** [kharchenkolab/numbat#55]
I wanted to use Numbat to investigate the copy number variations in a publicly available [10x lymphoma dataset](https://www.10xgenomics.com/resources/datasets/fresh-frozen-lymph-node-with-b-cell-lymphoma-14-k-sorted-nuclei-1-standard-2-0-0). My attempts ended with Numbat finding **no copy number variations** in this dataset, which presumably should have some. 

**Steps to reproduce:** 

1. Run a docker with Numbat: `docker run -v /home/jupyter/docker_test:/mnt/mydata -it pkharchenkolab/numbat-rbase:latest /bin/bash`

2. Download and extract the following files from 10x link: save the feature matrix along with barcodes and features from `lymph_node_lymphoma_14k_filtered_feature_bc_matrix.tar.gz` as `lymphoma_matrix.mtx`, `lymphoma_barcodes.tsv` and `lymphoma_features.tsv`; save the BAM file and its index from `lymph_node_lymphoma_14k_gex_possorted_bam.bam` as `lymphoma.bam` and `lymphoma.bam.bai`.

3. Inside the docker, run 
```
Rscript /numbat/inst/bin/pileup_and_phase.R --label lymphoma --samples lymphoma --bams /mnt/mydata/lymphoma.bam --barcodes /mnt/mydata/lymphoma_barcodes.tsv --outdir /mnt/mydata/lymphoma --gmap /Eagle_v2.4.1/tables/genetic_map_hg38_withX.txt.gz --snpvcf /data/genome1K.phase3.SNP_AF5e2.chr1toX.hg38.vcf --paneldir /data/1000G_hg38 --ncores 16
```
to generate an allele count file.

4. Prepare the matrix and allele count file to work with Numbat
```
mtx <- as(Matrix::readMM("/mnt/mydata/lymphoma_matrix.mtx"), "dgCMatrix")
df_allele_cnt <- read.csv("/mnt/mydata/lymphoma/lymphoma_allele_counts.tsv", sep = "\t")
features <- read.csv("/mnt/mydata/lymphoma_features.tsv", sep = "\t", header = F)
barcodes <- read.csv("/mnt/mydata/lymphoma_barcodes.tsv", sep = "\t", header = F)
dimnames(mtx) = list(features$V2, barcodes$V1)

duplicate_genes = duplicated(features$V2)
features_new = features[!duplicate_genes, ]
mtx_new = mtx[!duplicate_genes, ]
```
5. Run Numbat: 
```
run_numbat(mtx_new, ref_hca, df_allele_cnt, genome = "hg38", t = 1e-5, ncores = 4, plot = TRUE, out_dir = "/mnt/mydata/lymphoma_results")
```

**Expected result**:
I expected Numbat to find some copy number variations in this dataset.

**Actual result**:
Numbat runs for 1 iteration, then terminates with "No CNV after filtering - terminating" message (see attached image).

![photo1665699191](https://user-images.githubusercontent.com/113390633/200445767-d79c19a4-762f-4101-8928-731d4a14fe0d.jpeg)

Please help me understand the results I am getting: are there settings that should be different? Is the result expected for this dataset?

**Comment by teng-gao** [comment]
Thanks for the detailed report. We previously analyzed this sample before and it should find some CNVs. Could you attach the outputs (`bulk_subtrees_1.png`, `exp_roll_clust.png`, and `joint_post_1.tsv`) in the results folder?

**Comment by juliashay** [comment]
> Thanks for the detailed report. We previously analyzed this sample before and it should find some CNVs. 

That's good to know.

> Could you attach the outputs (`bulk_subtrees_1.png`, `exp_roll_clust.png`, and `joint_post_1.tsv`) in the results folder?

In my run, Numbat terminated before it generated the results folder and any of these files.

**Comment by teng-gao** [comment]
That would be surprising, because the output folder is created before any of the analysis steps are executed:

```
https://github.com/kharchenkolab/numbat/blob/main/R/main.R#L109-L112
```

Please double-check - I'm almost sure that the result folder shouldn't be empty.

**Comment by teng-gao** [comment]
Hi @juliashay ,

I was able to reproduce your results. The CNVs are filtered out because of the `max_entropy` threshold. You can check by

```
fread('~/lymphoma/lymphoma_results/joint_post_1.tsv') %>% distinct(seg, avg_entropy) %>% count(avg_entropy < 0.5)
```

This is also documented [here](https://kharchenkolab.github.io/numbat/articles/numbat.html#faq).

The uncertainty in single-cell posterior is high because of the high noise in expression logFC (`ref_hca` is not a great match for this dataset; better use a custom reference). Alternatively, change `max_entropy=0.8` and the workflow should succeed.
