### ISSUE TITLE
Barcodes pileup_and_phase

### ISSUE THREAD

**Issue by petrsh** [kharchenkolab/numbat#57]
Hi @teng-gao , 
thanks for developing this nice tool! I'm currently testing it and comparing it with the Copykat and inferCNV and unexpectedly getting bad results and weird errors for some samples. Before posting their description here, I wanted to check if one should use only barcodes for high-quality cells (i.e. after QC and doublet removal) during the pileup_and_phase step? I used all barcodes from the barcodes.tsv files from the filtered_feature_bc_matrix folders .... could this cause the issues?

**Comment by ahwanpandey** [comment]
Hello @petrsh and @teng-gao 

Just wanted to check; was the consensus to only use barcodes of high quality cells for pileup and subsequent Numbat analysis, or just to use all the barcodes in filtered_feature_bc_matrix folders?

Thank you,
Ahwan
