### ISSUE TITLE
No CNV remains after filtering 

### ISSUE THREAD

**Issue by petrsh** [kharchenkolab/numbat#58]
Follow-up to #57 

I’m running a pilot experiment with the objective to select the best tool for distinguishing between normal and malignant cells based on their CNV profile. I use data from this study 10.1016/j.molcel.2021.10.013.

I run sample SRR13914002 with hca_ref and with a custom ref using normal cells from the dataset. In both cases I got this:
"No CNV remains after filtering - terminating."

(I got same comment for another sample from so far six tested samples)

Here are log files - 
[log_custom_ref.txt](https://github.com/kharchenkolab/numbat/files/9974227/log_custom_ref.txt)
[log_hca_ref.txt](https://github.com/kharchenkolab/numbat/files/9974229/log_hca_ref.txt)

Bulk plots for custom ref:
![bulk_clones_1](https://user-images.githubusercontent.com/55283841/200916350-da693fcb-4711-4844-b7fd-0b3b7b7ba765.png)
![bulk_subtrees_1](https://user-images.githubusercontent.com/55283841/200916376-a7efabb7-601e-42e5-9d92-f375f3608ebe.png)

Bulk plots for  hca ref
![bulk_clones_2](https://user-images.githubusercontent.com/55283841/200916536-d9808813-381e-40a3-bafb-e1b346aa8c55.png)
![bulk_subtrees_2](https://user-images.githubusercontent.com/55283841/200916578-c7d09464-1fe9-4cef-997e-f95a11fa846a.png)

This is result from Copykat:
 
![image](https://user-images.githubusercontent.com/55283841/200915947-270fe58f-00ab-4f43-8e0c-72d1acde2f5c.png)

where ‘not available’ are malignant cells classified based on particular marker genes.

**Comment by teng-gao** [comment]
Thanks for this report. There seems to be a problem in the `pileup_and_phase` stage - many SNPs appear to be homozygous and somehow included in the allele profile. Is there a way you could share with me the BAM and barcode list so I can reproduce this?

**Comment by petrsh** [comment]
Thanks for quick replies! Unfortunately I'm afraid that I can't as access to these raw data is restricted...I have to check with my supervisor first.

**Comment by teng-gao** [comment]
I see. I think others have reported a similar problem before .. I'm happy to connect via a quick call today or tomorrow to know more about how the genotyping was performed. Let me know; My email is tgaoteng@gmail.com

**Comment by teng-gao** [comment]
Hi @petrsh,

I suspect your 10x lane was multiplexed - please see this [thread](https://github.com/kharchenkolab/numbat/issues/49#issuecomment-1306016829) here.

**Comment by petrsh** [comment]
I run it incorrectly. I set as a label a study ID and put all samples IDs and bams into one run of pileup_and_phase.R...however after that problem with 'No CNV remains after filtering' remained. Setting max.entropy = 1 solved that. Thank you for your assistance!
