### ISSUE TITLE
Running numbat on merged bam [smart-seq]

### ISSUE THREAD

**Issue by Laolga** [kharchenkolab/numbat#60]
Hi! I'm trying to run numbat on my smartseq data.
I’ve been using numbat before for my 10x data and it worked fine so the software part is not really the problem.

So the data was provided to be as a set of bam files. My understanding is that numbat treats 1 bam file as 1 sample and therefore if all my cells are coming from one sample, then the bam files should be merged.

So I’ve ran samtools merge with -r option too keep file name as a RG tag:
`samtools merge -r -O BAM --threads 20 rna_merged.bam STAR/*/*.bam`

Next with the same file names I created barcodes.tsv file

And then pileup:

`Rscript numbat/inst/bin/pileup_and_phase.R --label label --samples sample --bams rna_merged.bam --barcodes barcodes.tsv --outdir pileup --ncores 10 —smartseq <other args>`

And this step fails:

`During startup - Warning message:
Setting LC_CTYPE failed, using "C" 
Using genome version: hg38
Running pileup
[I::main] start time: 2022-11-14 15:31:04
[E::check_args] 'BAM'?' does not exist.
[E::main] error global settings
Error in value[[3L]](cond) : Pileup failed
Calls: tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
Execution halted`

Could you please advise what am I doing wrong?

**Comment by teng-gao** [comment]
Hi @Laolga ,

This is not officially supported yet but to run `--smartseq` mode, you can supply a txt file containing directories of bam files to `--bams` and a file containing cell names to `--barcodes` (each entry on its own line for both files). The `--samples` argument can just be one sample name.

https://github.com/kharchenkolab/numbat/blob/main/inst/bin/pileup_and_phase.R#L90-L105

**Comment by Laolga** [comment]
Great! Thank you for the reply

**Comment by cathalgking** [comment]
Hi @Laolga 
Did you get past this issue? I dont have the exact same issue but something simliar. When I try to run the preprocessing script I get the error ```Error in value[[3L]](cond) : Pileup failed
Calls: tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
Execution halted```

Have you any idea what would be causing this issue? thanks
