### ISSUE TITLE
Phasing failed with smartseq  input.

### ISSUE THREAD

**Issue by wangsky137** [kharchenkolab/numbat#61]
cat('Creating VCFs\n')
vcfs = lapply(samples, function(sample){vcfR::read.vcfR(glue('{outdir}/pileup/{sample}/cellSNP.base.vcf'), verbose = F)})

numbat:::genotype(label, samples, vcfs, glue('{outdir}/phasing'))

as smartseq cellsnp-lite only have one output, the vcfs would be rendered different.

I am wondering in the case of smartseq how should I do the genotype and phasing step

**Comment by teng-gao** [comment]
Hi @wangsky137 , 

Please see the instructions I added here for smart-seq:
https://kharchenkolab.github.io/numbat/articles/numbat.html#preparing-data

Thanks,
Teng
