### ISSUE TITLE
Interpreting of logFC and pHF for bulk_clone results

### ISSUE THREAD

**Issue by Summerhythm** [kharchenkolab/numbat#69]
Hi!

I used numbat and it works pretty well on several samples.
I was wondering if you would be willing to provide some interpretation of the logFC and pHF (on the right side of each bulk_clone results). My understanding is that logFC is the log fold change of observed cell expression and reference expression value, and the pHF means the paternal haplotype frequency of a SNP (and thus determines whether the CNV event is monoallelic or not). Is that correct?

Thanks,
Jack

**Comment by teng-gao** [comment]
Hi Jack,

Yes, logFC is analogous to logR and pHF is analogous to BAF (except that pHF is phased) as defined in traditional copy number analysis. For an explanation of how logR and BAF relate to different copy number states, here is a good diagram (from [stackoverflow](https://stackoverflow.com/questions/72380778/calculation-of-log-r-ratio-and-b-allele-frequency-and-manhattan-plot-from-snp-ar)):

<img width="982" alt="image" src="https://user-images.githubusercontent.com/13375875/204330837-b763e09d-a771-4f45-ad2c-b61cb9199e0a.png">

For the difference between pHF and BAF you can refer to Figure 1a of the [Numbat paper](https://www.nature.com/articles/s41587-022-01468-y):

<img width="762" alt="image" src="https://user-images.githubusercontent.com/13375875/204331927-ce782ea9-e6bb-4f40-b801-58190b532533.png">

Additional references:
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2652209/

**Comment by Summerhythm** [comment]
Hi Teng,

Sorry for the late reply. Got it, thank you very much for your detailed interpretation!

Yours,
Jack
