### ISSUE TITLE
Running numbat failed: Error in sendMaster(try(lapply(X = S, FUN = FUN, ...), silent = TRUE)): ignoring SIGPIPE signal

### ISSUE THREAD

**Issue by Summerhythm** [kharchenkolab/numbat#70]
Hi!

Thank you very much for developing this tools!
I have successfully ran numbat on several samples, but failed on a large one contained 32067 cells. When running numbat, I use the following codes on a workstation with 24 cores (48 threads) and more than 300G RAM:

```r
out <- run_numbat(
    count_mat = obs_dge, # gene x cell integer UMI count matrix 
    lambdas_ref = ref_internal, # reference expression profile, a gene x cell type normalized expression level matrix
    df_allele = allele_counts, # allele dataframe generated by pileup_and_phase script
    genome = "hg38",
    ncores = 24,
    plot = TRUE,
    out_dir = './numbat_result')
```

The results of bulk_clones_2 had been successfully generated, but then an error occurs:

```r
Running HMMs on 4 cell groups..
Retesting CNVs..
Retesting CNVs..
Retesting CNVs..
Retesting CNVs..
Running HMMs on 4 cell groups..
Testing for multi-allelic CNVs ..
0 multi-allelic CNVs found: 
Evaluating CNV per cell ..
Mem used: 23.3Gb
Error in sendMaster(try(lapply(X = S, FUN = FUN, ...), silent = TRUE)) : 
  ignoring SIGPIPE signal
Calls: run_numbat ... get_exp_post -> mclapply -> lapply -> FUN -> sendMaster
In addition: There were 23 warnings (use warnings() to see them)
Error in sendMaster(try(lapply(X = S, FUN = FUN, ...), silent = TRUE)) : 
  ignoring SIGPIPE signal
Calls: run_numbat ... get_exp_post -> mclapply -> lapply -> FUN -> sendMaster
In addition: There were 23 warnings (use warnings() to see them)
```

I have looked the numbat/R/main.R and see this inside the 'Running HMM' part:

```r
results = mclapply(
        bulks %>% split(.$sample),
        mc.cores = ncores,
        function(bulk) {
            bulk %>% analyze_bulk(
                t = t,
                gamma = gamma, 
                find_diploid = find_diploid, 
                run_hmm = run_hmm,
                allele_only = allele_only, 
                diploid_chroms = diploid_chroms,
                min_genes = min_genes,
                retest = retest, 
                verbose = verbose,
                segs_loh = segs_loh,
                exclude_neu = exclude_neu
            )
    })
```

Is there an error related to R multi-processing or large DGE?

Thanks,
Jack

**Comment by teng-gao** [comment]
Hello,

The error happened at the single-cell evaluation step ([`get_exp_post`](https://github.com/kharchenkolab/numbat/blob/main/R/main.R#L1283-L1305)). Most likely you ran out of memory (see this [thread](https://github.com/qiime2/q2-dada2/issues/119)). `mclapply` duplicates the entire workspace and uses 23.3*24 = 559.2Gb of memory in you case, so the workaround is to reduce number of cores used. Please try.

Best,
Teng

**Comment by Summerhythm** [comment]
Hi Teng,

Sorry for the late reply. Thank you very much for your quick help! I have successfully run numbat on this sample by applying this solutions!

Yours,
Jack
