### ISSUE TITLE
Mutate error at "Creating VCFs" stage of pileup_and_phase.R

### ISSUE THREAD

**Issue by AndyBlake** [kharchenkolab/numbat#71]
Hiya
I get this error :

Error in `mutate()`:
! Problem while computing `snp_index = 1:n()`.
✖ `snp_index` must be size 0 or 1, not 2.

at the "Creating VCFs" stage of pileup_and_phase.R

What should I check for to fix this?
Ta

**Comment by teng-gao** [comment]
Hi, 

This may be related to #67 .. could you try with the main github branch (v1.0.5) or the updated docker image?

**Comment by AndyBlake** [comment]
Pulled the latest docker and even updated from git just in case from within - same error - would this error be explained if there were more than one patient's data in the bam?

**Comment by teng-gao** [comment]
That’s posssible - Please paste the command you used

**Comment by AndyBlake** [comment]
inside the docker :

Rscript /numbat/inst/bin/pileup_and_phase.R --label Undetermined --samples Undetermined --bams /home/andrewblake/CancerCentre/SingleCellWorks/run_count/
outs/possorted_genome_bam.bam --barcodes /home/andrewblake/CancerCentre/SingleCellWorks/cellAnnotations.txt --outdir /home/andrewblake/CancerCentre/SingleCellWorks/numbat_ou
tput --gmap /Eagle_v2.4.1/tables/genetic_map_hg38_withX.txt.gz --snpvcf /data/genome1K.phase3.SNP_AF5e2.chr1toX.hg38.vcf --paneldir /data/1000G_hg38 --ncores 110

**Comment by teng-gao** [comment]
Is ‘cellAnnotations.txt’ in the correct format and only contain cells from one person? And have you checked if the phased VCFs look correct
