### ISSUE TITLE
Error in using external annotation in plot_phylo_heatmap

### ISSUE THREAD

**Issue by wangsky137** [kharchenkolab/numbat#72]
I was able to run the function with out additional annotation but 
nb$plot_phylo_heatmap(
  clone_bar = TRUE, 
  p_min = 0.9,
  annot=meta
)
when given a annotation data frame with one column name cell and the other of additional annotation the function seems give me error 

it goes into 
Error in data.frame(cell = names(annot), annot = unname(annot)) : 
  arguments imply differing number of rows: 2, 305

it seems it goes it  go through this  while my input is.data.frame is true
if (!is.data.frame(annot)) {
            annot = data.frame(
    			cell = names(annot),
    			Annotation = unname(annot)
    		)
        }
my annotation input is like following 
![image](https://user-images.githubusercontent.com/89659141/204415923-d277a76e-d0ed-47bc-8944-5cbc29cf5bd9.png)

**Comment by teng-gao** [comment]
Should be fixed in main branch now (02d42ca02f61d6bd4adc464294bfcf6eb407933d)
