### ISSUE TITLE
Error in h(simpleError(msg, call)) : 

### ISSUE THREAD

**Issue by zqingyuan** [kharchenkolab/numbat#73]
Dear Professor：
I have a problem about the use of numbat, the details are as follow, look forward to your reply.
Thanks,
Zhao

> out = run_numbat(
+     count_mat, # gene x cell integer UMI count matrix 
+     ref_internal, # reference expression profile, a gene x cell type normalized expression level matrix
+     allele_data, # allele dataframe generated by pileup_and_phase script
+     genome = "hg38",
+     t = 1e-2,
+     ncores = 4,
+     plot = TRUE,
+     out_dir = './test'
+ )
Filtering out 471 cells with 0 coverage
Running under parameters:
t = 0.01
alpha = 1e-04
gamma = 20
min_cells = 50
init_k = 3
max_cost = 529.5
max_iter = 2
max_nni = 100
min_depth = 0
use_loh = auto
multi_allelic = TRUE
min_LLR = 5
min_overlap = 0.45
max_entropy = 0.5
skip_nj = FALSE
diploid_chroms = 
ncores = 4
ncores_nni = 4
common_diploid = TRUE
tau = 0.3
check_convergence = FALSE
plot = TRUE
genome = hg38
Input metrics:
1765 cells
Mem used: 5.71Gb
Approximating initial clusters using smoothed expression ..
Mem used: 5.71Gb
number of genes left: 5
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 't': subscript out of bounds

**Comment by teng-gao** [comment]
Hi Zhao, 

I see the message "Filtering out 471 cells with 0 coverage" and "number of genes left: 5". It is probably because the gene names do not match between `ref_internal` and `count_mat`.
