### ISSUE TITLE
No CNV remains after filtering - terminating.

### ISSUE THREAD

**Issue by tinakeshav** [kharchenkolab/numbat#74]
Hi, 
Thank you for developing such a great package. 
I have a few samples coming from the same patient. Majority (~70%) of these samples fail with the following error, while 30% of them run perfectly fine. I'm taking TCells from the entire patient (Includes TCells from each sample) as background. 
For the 70% failure rate, the algorithm generally works until ```joint_post_1.tsv``` and has what seems to be pretty valid CNV predictions. In the accompanying screenshot, the top right image are CNVs inferred from bisulfite sequencing and the karyogram are scATAC-based CNVs from the same sample. 
What can I improve to ensure numbat runs on the majority of samples that are failing? 
The ones that do not fail have given me pretty solid results, so I look forward to finding a solution for the rest of them :) 
Thank you so much, 
Tina  

```R

out = run_numbat(
        count_mat_obs_sample, # gene x cell integer UMI count matrix
        normalized_mat_ref, # reference expression profile, a gene x cell type *normalized expression level* matrix
        df_allele, # allele dataframe generated by pileup_and_phase script
        genome = "hg38",
        t = 1e-5,
        ncores = ncores,
        plot = TRUE,
        out_dir = out_dir
)


Running under parameters:
t = 1e-05
alpha = 1e-04
gamma = 20
min_cells = 50
init_k = 3
max_cost = 3520.8
max_iter = 2
max_nni = 100
min_depth = 0
use_loh = auto
multi_allelic = TRUE
min_LLR = 5
min_overlap = 0.45
max_entropy = 0.5
skip_nj = FALSE
diploid_chroms =
ncores = 16
ncores_nni = 16
common_diploid = TRUE
tau = 0.3
check_convergence = FALSE
plot = TRUE
genome = hg38
Input metrics:
11736 cells
Mem used: 110Gb
Approximating initial clusters using smoothed expression ..
Mem used: 110Gb
number of genes left: 12284
running hclust...
Iteration 1
Mem used: 127Gb
Running HMMs on 5 cell groups..
Retesting CNVs..
Retesting CNVs..
Retesting CNVs..
Retesting CNVs..
Retesting CNVs..
Running HMMs on 3 cell groups..
Testing for multi-allelic CNVs ..
0 multi-allelic CNVs found:
Evaluating CNV per cell ..
Mem used: 113Gb
All cells succeeded
Expanding allelic states..
No multi-allelic CNVs, skipping ..
No multi-allelic CNVs, skipping ..
No multi-allelic CNVs, skipping ..
Building phylogeny ..
Mem used: 113Gb
No CNV remains after filtering - terminating.
Warning messages:
1: attributes are not identical across measure variables; they will be dropped
2: attributes are not identical across measure variables; they will be dropped
3: attributes are not identical across measure variables; they will be dropped
4: attributes are not identical across measure variables; they will be dropped
5: attributes are not identical across measure variables; they will be dropped
6: attributes are not identical across measure variables; they will be dropped
7: attributes are not identical across measure variables; they will be dropped
8: attributes are not identical across measure variables; they will be dropped
```

![Screen Shot 2M](https://user-images.githubusercontent.com/32367302/205677209-92f3632a-b3a4-4071-946a-9e8893bae507.jpg)

**Comment by teng-gao** [comment]
Hi Tina,

Thanks for the issue. This most likely is because the `max_entropy = 0.5` threshold is too stringent. This is explained in more detail in the [FAQ](https://kharchenkolab.github.io/numbat/articles/numbat.html#faq). You can check the `avg_entropy` column of `joint_post_1.tsv` for the specific values of your CNV calls.

Best,
Teng

**Comment by teng-gao** [comment]
Hi Tina, 

Yes, this is expected. `max_entropy` essentially serves as a filter that excludes low-confidence CNVs from phylogeny construction. If none of the CNVs pass the threshold Numbat terminates. You can see this in your data by noting that in the failed samples none of the CNVs have entropy < 0.5. For datasets that have a lot of focal CNVs or low coverage per cell, a higher threshold is more suitable (e.g. 0.8).

**Comment by tinakeshav** [comment]
Thank you Teng! Your advice helped me get every sample to work. 
Unfortunately now, I am attempting clonal analysis of these samples and get the following error: 
```
out = run_numbat(
                count_mat_obs_sample,
                normalized_mat_ref,
                df[samples] %>% bind_rows %>% dplyr::filter(cell %in% non_ref_cells),
                genome = "hg38",
                t = 1e-5,
                ncores = 30,
                max_entropy = 0.8,
                multi_allelic = TRUE,
                out_dir = out_dir
)
 Inconsistent SNP genotypes; Are cells from two different individuals mixed together?
Error in log_err("Inconsistent SNP genotypes; Are cells from two different individuals mixed together?") :
  Inconsistent SNP genotypes; Are cells from two different individuals mixed together?
```

The overall CNV landscape of these samples are similar. The cells are also more similar to each other than when there is data from other patients. I am quite confident that the samples haven't been mislabeled and come from the same individual.
Any input for how I can go about resolving this? 
Thank you so much, 
Tina

**Comment by tinakeshav** [comment]
So I've written your pileup_and_phase.R  in Snakemake format because I have too many samples and figured it was a bit easier to keep track of the workflow using snakemake.  I basically broke up pileup_and_phase.R  to individual Rscripts that Snakemake runs. 


What I'd love to clarify with you is which step of your pileup_and_phase.R can run independently for every sample and which steps depend on all samples? I listed some assumptions that may likely be wrong, but I would appreciate your input. 

- It's okay to run cellsnp-lite independently for each sample (10x) 
- It's okay to run numbat::genotype independently for each sample 
- It's okay to run eagle independently for each sample
--> For clonal analysis, I should rather pass all my samples to rule numbat_allele_counts (uses the last portion of your pileup_and_phase.R script) instead of every sample individually

Thank you so much!
Tina

**Comment by teng-gao** [comment]
Hi Tina,

Everything I highlight here should be run jointly for samples of the same individual:

https://github.com/kharchenkolab/numbat/blob/main/inst/bin/pileup_and_phase.R#L150-L253

This includes your second and third bullet points.

**Comment by tinakeshav** [comment]
Thank you so much! I got everything to work :) 

Though because of the number of samples there's an unfortunate memory error when constructing the phylogeny. I guess the only solution is now to subset the data.
```
Building phylogeny ..
Mem used: 98.1Gb
Using 13 CNVs to construct phylogeny
Error in ape::nj(dist_mat) :
  cannot allocate memory block of size 134217728 Tb
```
