### ISSUE TITLE
when submit pileup_and_phase.R in docker it says[E::check_args] '/Users/sample_alignments.bam' does not exist.

### ISSUE THREAD

**Issue by yintz** [kharchenkolab/numbat#75]
the file in did in the folder, but it states that

submit this 
Rscript /numbat/inst/bin/pileup_and_phase.R \
--label 'xxxx' \
--samples sample_alignments \
--bams /Users/sample_alignments.bam \
--barcodes /Users/barcodes.tsv \
--outdir /Users/dockfolder \
--gmap /Users/genetic_map_hg38_withX.txt.gz \
--snpvcf /Users/genome1K.phase3.SNP_AF5e2.chr1toX.hg38.vcf \
--paneldir /Users//1000G_hg38 \
--ncores 5

Using genome version: hg38
Running pileup
[I::main] start time: 2022-12-07 08:04:02
[E::check_args] '/Users/sample_alignments.bam' does not exist.
[E::main] error global settings
[E::main] Quiting...
[I::main] Version: 1.2.2 (htslib 1.16)
[I::main] CMD: cellsnp-lite -s /Users/sample_alignments.bam -b /Users/barcodes.tsv -O /Users/pileup/sample_alignments -R /Users/genome1K.phase3.SNP_AF5e2.chr1toX.hg38.vcf -p 5 --minMAF 0 --minCOUNT 2 --UMItag Auto --cellTAG CB
[I::main] end time: 2022-12-07 08:04:02
[I::main] time spent: 0 seconds.
Error in value[[3L]](cond) : Pileup failed
Calls: tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
Execution halted

what should  I do?

**Comment by teng-gao** [comment]
I think you probably didn't mount the local directory when you launched docker. Please make sure you are doing the binding correctly like we described in the [guide](https://kharchenkolab.github.io/numbat/articles/numbat.html#docker).

You can also check out the documentation on [how Docker binding mount works](https://docs.docker.com/engine/reference/commandline/run/).
