### ISSUE TITLE
Error during pileup_and_phase.R - barcodes not identified

### ISSUE THREAD

**Issue by sbamopoulos** [kharchenkolab/numbat#77]
Hello numbat team,

when running the preprocessing script for nubmat (pileup_and_phase.R) I encounter the error previous posters have also encountered:

Using genome version: hg38
Running pileup
[I::main] start time: 2022-12-07 21:24:02
[I::main] loading the VCF file for given SNPs ...
[I::main] fetching 9668 candidate variants ...
[I::main] mode 1: fetch given SNPs in 1633 single cells.
[I::csp_fetch_core][Thread-27] 2.32% SNPs processed.
[...]
[I::csp_fetch_core][Thread-0] 98.02% SNPs processed.
[I::main] All Done!
[I::main] end time: 2022-12-07 21:24:15
[I::main] time spent: 13 seconds.
character(0)
Creating VCFs
Error in h(simpleError(msg, call)) :
  error in evaluating the argument 'x' in selecting a method for function 'as.matrix': arguments imply differing number of rows:                       0, 31

**My input file is a BAM file sequenced on the BD Rhapsody platform and aligned with STAR solo (droplet-based single-cell RNASeq)**

I use the following command:

Rscript pileup_and_phase.R \
    --label "01" \
    --sample "01" \
    --bams file.BAM \
    --barcodes barcodes.txt \
    --outdir $HOME/work/numtest/01 \
    --gmap $HOME/work/refs/genetic_map_hg38_withX.txt \
    --snpvcf $HOME/work/refs/genome1K.phase3.SNP_AF5e2.chr1toX.hg38.vcf \
    --paneldir $HOME/work/refs/1000G_hg38 \
    --cellTAG "CB" \
    --UMItag "MR" \
    --ncores 8 \
    --eagle $HOME/work/miniconda/envs/numbatenv/bin

I run the pileup script manually and was able to narrow down the error, it occurs directly after running cellsnp-lite, because the .vcf file has 0 samples:

> vcfs
[[1]]
***** Object of Class vcfR *****
**0 samples**
1 CHROMs
142 variants
Object size: 0 Mb
NaN percent missing data
*****        *****         *****

(I used a shortened snp file to reproduce the error, that is why it is only 1 chromosome and 142 variants

It seems like the cell barcodes are recognized since the number of cells displayed (1663) is correct. Some specifics on the input files:
- Input BAM: multiplexed BAM file, where CB:Z: Tag denotes cell barcodes, ST:Z denotes the samples (01-12) and MR the UMI. 
- Aligment was done on Ensembl GRCh38 (GENCODE 29)
- The barcode is a plain text file that has one barcode per line (they are numbers in BD Rhapsody), like so:

850570
243761
39999
360647
589619

- the snp reference file is the one you have provided in the intro, I only changed the chromosome names from e.g. "1" to "chr1" to match the BAM file chromosomes

The tool seems to recognize the BAM file since it produces read counts in the vcf file, but there isn't one column per cell barcode, as I would expect, like the following:

##fileformat=VCFv4.2
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO
chr1    629218  .       A       G       .       PASS    AD=3;DP=70;OTH=0
chr1    629482  .       T       C       .       PASS    AD=0;DP=2;OTH=0
chr1    629626  .       T       C       .       PASS    AD=0;DP=2;OTH=0
chr1    629906  .       C       T       .       PASS    **AD=7;DP=6689;OTH=21**
chr1    630026  .       C       T       .       PASS    AD=1;DP=6;OTH=0
chr1    630084  .       T       C       .       PASS    AD=0;DP=4;OTH=0
chr1    630110  .       T       C       .       PASS    AD=2;DP=2;OTH=1
chr1    630128  .       G       A       .       PASS    AD=0;DP=3;OTH=0

I already tried the script on a filtered BAM file with barcodes from only one patient and changing the CB barcodes to cellranger format (adding a -01) at the end, as well as changing the ST:Z barcode to BC:Z which seems to be the sample barcode for cellranger. It all produces the same error. 

I would really appreciate some input on this issue, I have been unable to solve it despite intense effort.

Best
Stefan

**Comment by teng-gao** [comment]
Hello,

Thanks for the issue. First, you should use `--eagle` to pass the path to the `eagle` binary instead of a folder that contains it. e.g., `--eagle /home/tenggao/bin/eagle`. 

If that doesn't resolve the issue, please clarify:

1.  In the output folder, do you see normal-sized files under `pileup/`?  Is `cellSNP.base.vcf` empty? If so, cellsnp-lite has run successfully. 

2. Do you see non-empty `{sample}_chr*.vcf.gz` files under `phasing/`? These are the files before `eagle2` was run. If so, genotyping was successful.

3. If there are `{sample}_chr*.phased.vcf.gz` files under `phasing/`, then `eagle2` phasing worked successfully.

Best,
Teng

**Comment by sbamopoulos** [comment]
Hi Teng,

sorry for the late reply it took some while figuring out the problem. It seems that as it is currently written the _pileup_and_phase.R_ script does not work as intended when the input BAM has a "chr" prefix (i.e. "chr1", "chr2" etc.). Since the chr_prefix variable is not modifiable it is always true and the script adds a "chr" whether it is already present or not. The part until cellsnp-lite works fine, but the script fails at _numbat::genotype()_. 

I have rewritten the _pileup_and_phase.R_ script, as well as the called upon functions in _genotype.R_. Not it automatically checks for the prefix and returns the same output regardless of it. 

If you would like I can share the rewritten code with you, or do a pull request? (I am not very familiar with GitHub, but have cloned and modified the files and could upload them)

**Comment by teng-gao** [comment]
Hi @sbamopoulos,

Yes, a pull request would be awesome. Also easier for us to give credit :) 

Thanks,
Teng

**Comment by sbamopoulos** [comment]
Hi Teng,

I think you need to grant me permission for the PR? I just tried to git push and got:

ERROR: Permission to kharchenkolab/numbat.git denied to sbamopoulos.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Please advise me on how to proceed.

Best
Stefan

**Comment by teng-gao** [comment]
You can first fork the repo first and then create a PR. Please refer to instructions here:

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request?tool=webui

**Comment by sbamopoulos** [comment]
Hi Teng,

I created a pull request: 
https://github.com/kharchenkolab/numbat/pull/85

Best
Stefan

**Comment by teng-gao** [comment]
Thanks, merged!

**Comment by teng-gao** [comment]
Hmm, this doesn't work on my end. The conventional 10x BAM usually has a chr prefix and doesn't have issues. Are you sure it's the reason? 

The conventions of prefixes are:

1000G SNP VCF: no
10x BAM: yes (most common) and no (some)
1000G phasing panels (hg38/hg19): yes
pileup VCFs produced by `cellsnp-lite`: depends on the 10x BAM
VCFs produced by `pileup_and_phase`: yes

`cellsnp-lite` doesn't care if the prefixes match between the VCF and the BAM or not, and adheres to the BAM convention if there's a mismatch. `eagle2` does require that the prefixes match between the VCF and the reference panel, so we always add chr prefix to VCFs created by `pileup_and_phase`, regardless of the convention of the input BAM/VCF.

**Comment by sbamopoulos** [comment]
Hi Teng,

yes I am positive that the problem was the chr prefix, since I tested the pileup script after removing the prefix from the BAM and it ran through. 

The version you have now in the devel branch works for my input (BAM and 1000G SNP VCF both with chr prefix). However, the VCF in the pileup folder has a chr prefix, since it's always added in in the make_vcf_chr function if chr_prefix is always TRUE:

if (chr_prefix) {
        vcf_chr@fix[,1] = paste0('chr', vcf_chr@fix[,1])
}

or do you mean a different file with "pileup VCFs produced by cellsnp-lite"?

I am unsure as to why you pass a chr_prefix argument to genotype and make_vcf_chr if you always add a prefix before phasing anyway. Do you use the same functions for other applications? 

I wasn't aware that eagle2 always requires a match between VCF and panel, this explains why you got an error using my version. It probably occurred in BAM files without chr prefix? 

As a side note I find it very unintuitive that the genetic_map_hg38_withX.txt has to have no prefix, regardless of whether or not a chr prefix is present in the input vcf. It would have helped me if there was a small note regarding that, since I initially thought that all files need to have matching chr prefix and added it to the genetic map. 

Best
Stefan

**Comment by teng-gao** [comment]
> The version you have now in the devel branch works for my input (BAM and 1000G SNP VCF both with chr prefix). 

That's good, thanks for confirming.

> However, the VCF in the pileup folder has a chr prefix, since it's always added in in the make_vcf_chr function if chr_prefix is always TRUE:

By the "pileup VCFs produced by cellsnp-lite" I mean `cellSNP.base.vcf` under `pileup/`. Note that this is different than the VCF file that `make_vcf_chr` produces which is in `phasing/`.

> I am unsure as to why you pass a chr_prefix argument to genotype and make_vcf_chr if you always add a prefix before phasing anyway. Do you use the same functions for other applications?

That's fair, will remove this in the future

> As a side note I find it very unintuitive that the genetic_map_hg38_withX.txt has to have no prefix, regardless of whether or not a chr prefix is present in the input vcf. It would have helped me if there was a small note regarding that, since I initially thought that all files need to have matching chr prefix and added it to the genetic map.

I see. The genetic map file comes with Eagle2 so we didn't want to modify that ..
