### ISSUE TITLE
Error with "diploid_chroms"

### ISSUE THREAD

**Issue by Romeo1-1** [kharchenkolab/numbat#81]
Hello and thank you for this very useful package !

I am trying to use your package on scRNAseq of cancer cells. For a number of patients I have scDNAseq data and I know that some chromosomes are diploid. I thought that entering them would help to get more precise informations on other chromosomes, but I get an error.

Here is the complete code I run. I ran the pileup & phase script using the Docker versions on the 2 samples together. They are from the same patient, before and after treatment

```
P1_pre_data <- Read10X(data.dir = "P1_pre/outs/filtered_feature_bc_matrix/")
P1_post_data <- Read10X(data.dir = "P1_post/outs/filtered_feature_bc_matrix/")

P1_post_data@Dimnames[[2]] = gsub("1", "2", P1_post_data@Dimnames[[2]])

merged_data = cbind(P1_pre_data , P1_post_data )

P1_pre_pileup = read.csv(gzfile("numbat/P1/P1_pre_allele_counts.tsv.gz"), sep = '\t')
P1_post_pileup = read.csv(gzfile("numbat/P1/P1_post_allele_counts.tsv.gz"), sep = '\t')

P1_post_pileup$cell = gsub("1", "2", P1_post_pileup$cell)

merged_pileup = rbind(P1_pre_pileup , P1_post_pileup )

bulk = get_bulk(
  count_mat = merged_data,
  lambdas_ref = ref_hca,
  df_allele = merged_pileup,
  gtf = gtf_hg38
)

seg_loh = bulk %>% detect_clonal_loh(t = 1e-6)

out = run_numbat(
  merged_data
  ref_hca
  merged_pileup
  segs_loh = segs_loh,
  genome = "hg38",
  t = 1e-6,
  diploid_chroms = c(2,4,5,6),
  max_entropy = 0.8, 
  out_dir = 'Output/P1_test',
  ncores = 20,
  plot = TRUE,
)
```
And here's the error 

```
Running under parameters:
t = 1e-06
alpha = 1e-04
gamma = 20
min_cells = 50
init_k = 3
max_cost = 3146.1
max_iter = 2
max_nni = 100
min_depth = 0
use_loh = auto
multi_allelic = TRUE
min_LLR = 5
min_overlap = 0.45
max_entropy = 0.8
skip_nj = FALSE
diploid_chroms = 2,4,5,6
ncores = 20
ncores_nni = 20
common_diploid = TRUE
tau = 0.3
check_convergence = FALSE
plot = TRUE
genome = hg38
Input metrics:
10487 cells
Mem used: 13.3Gb
Approximating initial clusters using smoothed expression ..
Mem used: 13.3Gb
number of genes left: 8597
running hclust...
Iteration 1                                                                                                                          
Mem used: 13.3Gb
Running HMMs on 5 cell groups..
Error in mutate(., state = ifelse(loh, "del_2_up", state)) : 
  Problem while computing `state = ifelse(loh, "del_2_up", state)`.
? The error occurred in group 1: CHROM = 1.
Caused by error in `ifelse()`:
! 'list' object cannot be coerced to type 'logical'

Error in `group_by()`:
! Must group by variables found in `.data`.
Column `seg` is not found.
Column `sample` is not found.
Run `rlang::last_error()` to see where the error occurred.
Warning message:
In mclapply(bulks %>% split(.$sample), mc.cores = ncores, function(bulk) { :
  all scheduled cores encountered errors in user code`

```
Interestingly, when I do not input anything under "diploid_chroms", then the script works perfectly. Do you have any idea what would cause this ?

Thank you very much in advance for your help,

**Comment by teng-gao** [comment]
Hi @Romeo1-1,

Are you able to give a reproducible input example for this error (doesn't have to be full data)? Please feel free to share in private via email.

 Best,
Teng

**Comment by Romeo1-1** [comment]
Sure ! At what email adress should I send the link ?

Thank you very much,

Rémi

**Comment by teng-gao** [comment]
You can use tgaoteng@gmail.com.

**Comment by aranham** [comment]
I have the same issue if I provide a diploid chrom list and use the protocol for detecting clonal LOH in cell line data. If I do not detect clonal LOH, I can run numbat successfully. Would appreciate any thoughts on being able to both provide a diploid chrom list and detect clonal LOH.

**Comment by teng-gao** [comment]
@aranham Sure, feel free to share the input for this example too, and the full script for `run_numbat`. Thanks!

**Comment by aranham** [comment]
Shared on email. Thanks!

**Comment by teng-gao** [comment]
Hi @Romeo1-1 and @aranham ,

Thanks for catching this error. The main branch should now fix this (docker will be updated in the next version release). Please let me know if the issue persists.

Thanks,
Teng
