### ISSUE TITLE
Christophe's comments

### ISSUE THREAD

**Issue by teng-gao** [kharchenkolab/numbat#9]
Raised by @GeorgescuC:

- [x] there are a number of warnings (14) about overriding imports. You may want to use a file to set the imports method by method for dependencies so as to be sure that the correct method is the one loaded by the package in the end. Roxygen2 will be able to automatically update your NAMESPACE file based on those too. For example, in infercnv, we have that in the R/inferCNV_constants.R file.

- [x] The example data should probably not be automatically loaded with the package, but instead have it load when calling "data()". This will prevent potential conflicting/overriding variable names and improve loading speed.
   - need to remove anyway

- [x] I get the following warning, which might not be due to Numbat but to a dependency
Warning messages:
1: Unknown or uninitialised column: `n_states`.
2: Unknown or uninitialised column: `n_states`.
3: Unknown or uninitialised column: `n_states`.
4: The `x` argument of `as_tibble.matrix()` must have unique column names if `.name_repair` is omitted as of tibble 2.0.0.
Using compatibility `.name_repair`.
    - The name_repair warning comes from treeio - probably needs to be fixed externally
    - bbinom NA warning is from optim function of theta laplace approx, L-FGBS-R is trying theta > 0.5

- [x] In the example, I would not put an output path directly in the home directory, but instead use tempdir()/tempfile(), or use a location relative to the current working directory.

- [x] In the example, the "res = fetch_results()" step does not have the out_dir value set.

- [x] I think a dependency seems to be missing from the list, as I was able to install/load Numbat but got the following when first running it (which was resolved by installing the package):
> res = fetch_results("~/results/test", i = 2)
Error in fread(f) :
 To read gz and bz2 files directly, fread() requires 'R.utils' package which cannot be found. Please install 'R.utils' using 'install.packages('R.utils')'
There could be others that I happened to already have installed. The easiest way to figure out missing requirements would be to test in a virtual env/docker.

- [x] In the plotting step, "library(ggplot2)" needs to be loaded first to add the title.

- [x] The example final plot does not have the 1/2/3 groupings (both the color bar and the legend are missing for me) as shown on the wiki.

**Comment by teng-gao** [comment]
The `name_repair` warning comes from treeio - probably needs to be fixed externally

**Comment by evanbiederstedt** [comment]
RE: data

Discuss on Slack

Given the 5MB CRAN limit, I'd recommend we remove everything from `/data`. We can create a drat repo with this data which users can work with, similar to our other R packages e.g. https://github.com/kharchenkolab/conospanel, https://github.com/kharchenkolab/simulatedNMF, https://github.com/kharchenkolab/p2data

**Comment by evanbiederstedt** [comment]
RE: 
>  there are a number of warnings (14) about overriding imports. You may want to use a file to set the imports method by method for dependencies so as to be sure that the correct method is the one loaded by the package in the end. Roxygen2 will be able to automatically update your NAMESPACE file based on those too. For example, in infercnv, we have that in the R/inferCNV_constants.R file.

Use `importFrom` to resolve these. 
The issue is that the function names in the libraries with `import` are clashing. 

Note we'll have to move some of these libraries to `Suggests` for CRAN anyways, and then check if these are installed with `requireNamespace`. Viktor has a nice function here we could steal:

https://github.com/kharchenkolab/cacoa/blob/072278609f6d5f73cd9f1912403d33161017de00/R/utils.R#L15-L39
