### ISSUE TITLE
`snp_index` must be size 0 or 1, not 2. [error during run_numbat()]

### ISSUE THREAD

**Issue by laijen000** [kharchenkolab/numbat#90]
When running `out_5902 = run_numbat(count_mat, ref_internal, df_allele, genome='hg38',t=1e-5,ncores=ncores,plot=TRUE,out_dir=paste0(outdir,'/5902'))
`
I'm getting the error: 
```
Error in `mutate()`:
! Problem while computing `snp_index = 1:n()`.
✖ `snp_index` must be size 0 or 1, not 2.
Backtrace:
     ▆
  1. ├─numbat::run_numbat(...)
  2. │ └─numbat::annotate_genes(df_allele, gtf)
  3. │   └─... %>% distinct(snp_index, .keep_all = TRUE)
  4. ├─dplyr::distinct(., snp_index, .keep_all = TRUE)
  5. ├─dplyr::arrange(., snp_index, gene)
  6. ├─dplyr::left_join(., gtf %>% mutate(gene_index = 1:n()), by = c("gene_index"))
  7. ├─dplyr::left_join(...)
  8. ├─dplyr:::left_join.data.frame(...)
  9. │ └─dplyr::auto_copy(x, y, copy = copy)
 10. │   ├─dplyr::same_src(x, y)
 11. │   └─dplyr:::same_src.data.frame(x, y)
 12. │     └─base::is.data.frame(y)
 13. ├─snps %>% mutate(snp_index = 1:n()) %>% ...
 14. ├─dplyr::select(., snp_index, snp_id)
 15. ├─dplyr::mutate(., snp_index = 1:n())
 16. ├─dplyr:::mutate.data.frame(., snp_index = 1:n())
 17. │ └─dplyr:::mutate_cols(.data, dplyr_quosures(...), caller_env = caller_env())
 18. │   ├─base::withCallingHandlers(...)
 19. │   └─mask$eval_all_mutate(quo)
 20. ├─dplyr:::dplyr_internal_error(...)
 21. │ └─rlang::abort(class = c(class, "dplyr:::internal_error"), dplyr_error_data = data)
 22. │   └─rlang:::signal_abort(cnd, .file)
 23. │     └─base::signalCondition(cnd)
 24. └─dplyr (local) `<fn>`(`<dpl:::__>`)
 25.   └─rlang::abort(...)
```

run_numbat() worked for 4 samples, but is producing this error for 2 samples. I am attaching the error log here! You can see it ran fine for 4 samples but produced this error for the 5th sample. I ran run_numbat() separately on the final sample and it also produced this error. The pileup and phase vcf files for the 2 problematic samples are not empty. 

[20230108_numbat_R_singularity_3069135.txt](https://github.com/kharchenkolab/numbat/files/10375274/20230108_numbat_R_singularity_3069135.txt)

**Comment by teng-gao** [comment]
Thanks. Best way to debug is to run `annotate_genes(df_allele, gtf_gh38)` outside of the `run_numbat` function and see if you can reproduce the error. If so, you can step through the code to see what the problem was:

https://github.com/kharchenkolab/numbat/blob/bf95e2aa693b5665b97b8ec1371443a41c81c17c/R/diagnostics.R#L76-L116

**Comment by laijen000** [comment]
Thank you for the suggestion. I ran annotate_genes() and there was no error. The resulting df_allele looks good. I'll try running run_numbat() again, but please let me know you have other suggestions! Thank you!

**Comment by teng-gao** [comment]
It's unclear to me which sample had the error from the logs .. `annotate_genes` is only called once in the workflow:

https://github.com/kharchenkolab/numbat/blob/main/R/main.R#L85
