### ISSUE TITLE
p_cnv threshold for event calling 

### ISSUE THREAD

**Issue by laijen000** [kharchenkolab/numbat#94]
thank you for the great tool! 

I am wondering if a specific p_cnv threshold was used for event calling in the original manuscript (example, for Figure 2 event calling and performance validation). 

Similarly, what is the lowest p_cnv that numbat reported in the joint_df_* file for a true positive event? 

I would like to compare the burden of somatic CNVs in 2 groups and want to quantify the # of events per group based on a p_cnv threshold.

**Comment by teng-gao** [comment]
Hello, 

We actually only just used a minimum LLR cutoff of 5 (default setting; more details in the methods) in the paper. `p_cnv` is a score for CNV events in single cell whereas LLR is for pseudobulk CNV detection. When plotting `phylo_heatmap`, numbat by default uses `p_cnv > 0.9` as threshold for plotting the event in any given cell. I think that any `p_cnv` cutoff between `[0.5, 1)` is reasonable.
