### ISSUE TITLE
Mouse genetic background SNP

### ISSUE THREAD

**Issue by zqzneptune** [kharchenkolab/numbat#96]
Hello, 

While following the [Mouse tutorial](https://kharchenkolab.github.io/numbat/articles/mouse.html#preparing-input) Step 1, we couldn't find the exact match from the listed mouse strains is UCSC SNP VCFs. 

According to our lab technicians, the mouse strains we used are "C57BL/6J", while the closest match in the UCSC VCFs is "C57BL_10J" or "C57BL_6NJ". Maybe these are minor naming conflicts.

Regardless, will selecting different/unmatched genetic information (VCFs) affect CNV estimation by numbat?

Thanks,
Johnson

**Comment by zqzneptune** [comment]
Thanks, Teng, for your reply!

I have confirmed with our lab technician, that the mouse strain is purely *C57BL/6J*. Does that mean we cannot proceed with numbat?

Johnson

**Comment by teng-gao** [comment]
Unfortunately yeah Numbat wouldn't work very well because of the lack of heterozygous SNPs in inbred mouse strains.
