### ISSUE TITLE
Numbat error with custom reference

### ISSUE THREAD

**Issue by cv55** [kharchenkolab/numbat#97]
Hello, thanks for the great tool.
I am trying to use Numbat using the average of my cells as reference. I use the provided function aggregate_counts(..), but i keep getting the error:

Error in `mutate()`:
! Problem while computing `p = t.test.pval(...)`.
ℹ The error occurred in row 1.
Caused by error in `t.test.default()`:
! data are essentially constant
Traceback: ...

This is the first few reference genes and the annotation file to run the aggregate_counts().

![Screenshot 2023-01-19 at 16 45 09](https://user-images.githubusercontent.com/18632504/213487652-05c75674-b1ee-41cc-a46e-5951b8c11b92.png)
![Screenshot 2023-01-19 at 16 45 18](https://user-images.githubusercontent.com/18632504/213487692-4cb1d71a-4fb3-4c6a-b04d-4ee6efab279d.png)

**Comment by teng-gao** [comment]
Hello, the error message you show might suggest that you're using another function called `aggregate_counts` from a different package. You can try `numbat::aggregate_counts` instead.

Your reference gene should be a count matrix not normalized rates. Please refer to `numbat::count_mat_ref` and `numbat::annot_ref` for examples.
